### ISSUE TITLE
Broken tablet pen eraser

### ISSUE THREAD

**Issue by Industrality** [drawpile/Drawpile#368] opened 2016-10-15 19:22 UTC
When you use the tablet pen to switch between brush and eraser (by flipping the pen). It works once when you go from pen to eraser, but then breaks entirely not allowing you to switch from eraser to pen and vice versa. This issue is present in 1.0.3 1.0.4 and 1.0.5 . The last version it worked in was 1.0.2.

**Comment by soljak** [comment] 2016-11-04 20:54
Yeah I'm having this same issue. Some of my drawing companions have just kept with the last working version to avoid this issue. I was hopeful that this issue was going to be resolved with this update, but I guess no luck on that yet.

**Comment by dixonte** [comment] 2016-11-07 05:39
I am also experiencing this issue.

**Comment by callaa** [comment] 2016-12-11 11:17
There were no changed made to the tablet code in version 1.0.3, so the bug must originate in the bundled Qt version (which did change.) Unfortunately, this means fixing it is very difficult for me.

**Comment by wamserma** [comment] 2017-02-07 20:38
Duplicate of #341 ;)

**Comment by soljak** [comment] 2017-02-26 02:31
This issue is still present in 2.0 unfortunately.

**Comment by callaa** [comment] 2018-02-14 15:33
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Closed by callaa** 2018-02-14 15:33 UTC
Labels: Tablet
