### ISSUE TITLE
Navigator changing size when pressing Tab

### ISSUE THREAD

**Issue by HamousOnWheels** [drawpile/Drawpile#755] opened 2019-05-04 20:48 UTC
Hiding and unhiding docks repeatedly will gradually shrink or enlarge the navigator. It's fairly hard to reproduce consistently since behavior is changed and sometimes stopped by moving the docks around. But after a program restart it consistently exhibits shrinking at my preferred spot for the navigator (top left). Only happens with a docked navigator, both on the left and right side.

![navenlarge](https://user-images.githubusercontent.com/34580619/57184610-35627f80-6ebe-11e9-9541-a2e40767fb5b.gif)

![navshrink](https://user-images.githubusercontent.com/34580619/57184612-35627f80-6ebe-11e9-984b-524c37da808d.gif)

![navshrinkright](https://user-images.githubusercontent.com/34580619/57184613-35627f80-6ebe-11e9-8ceb-3c84cec2b6eb.gif)

Tested on windows with versions 2.1.7 and 2.1.8.

**Comment by fuzzn8r** [comment] 2019-11-25 04:10
I am also experiencing this issue. I've noted this behavior on closing and opening the chat window.

Windows 10, drawpile version 2.1.14

**Comment by notfood** [comment] 2019-12-25 20:31
This issue appears to have been fixed. At least, I can't reproduce it anymore. Can you confirm?

**Comment by HamousOnWheels** [comment] 2020-01-04 00:23
In version 2.1.15 I'm still having this issue (windows 7).

**Comment by askmeaboutlo0m** [comment] 2023-03-23 13:08
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming in Drawpile 2.2.

**Closed by askmeaboutlo0m** 2023-03-23 13:08 UTC
Labels: Bug
