### ISSUE TITLE
Drawpile pen sensitivity bug

### ISSUE THREAD

**Issue by Mhuyo** [drawpile/Drawpile#544] opened 2018-01-20 21:28 UTC
So I have a friend that tried to use drawpile recently and this happens:

https://media.giphy.com/media/3o7522uXfJy6mLCJMI/giphy.gif

She's using a yiynova msp19u+ and this problem happened just after actualizing the new update of windows 10 (it used to work fine before) also, it only happens with drawpile.

We tried:

- Restarting computer
- Re- installing Drawpile
-  Messing with user interface

**Comment by callaa** [comment] 2018-01-20 22:16
Duplicate of issue #531

Currently, the known workaround is to uncheck the "scroll with finger" option in the preferences. Checking "enable bug workarounds" may be needed too.

The problem is apparently caused by Windows now generating touch events instead of or in addition to pen events.

**Closed by callaa** 2018-01-20 22:16 UTC
