### ISSUE TITLE
Jump to user location in canvas when clicking on its name at the users list

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1132] opened 2023-08-13 20:10 UTC
Usability:
It would be handy to have the ability to jump directly to where the user is active just by clicking on its name.

Example: I'm talking with Bob in chat. When I click Bob's name in the users list, my "camera" jumps directly to its position on the canvas.

**Comment by askmeaboutlo0m** [comment] 2023-08-13 21:26
Duplicate of #934. But yeah, this could be implemented, the protocol in Drawpile 2.2 has a command reserved for user interactions like these.

**Closed by askmeaboutlo0m** 2023-08-13 21:26 UTC
