### ISSUE TITLE
Chat resize itself after restarting

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1106] opened 2023-07-08 03:39 UTC
Not sure if this was brought up or noticed, but in Windows the chat size reverts itself after exiting out of it when you try to minimize the length to the smallest it can go before it decides to hide completely. It doesn't happen when the chat is made bigger, only when you try to have it smaller. I don't know if this is intentional with the chat being updated (I think).

![Screenshot_2](https://github.com/drawpile/Drawpile/assets/51433534/03fb812a-069c-45b6-a2b4-d1d8f53fb1cb)

![Screenshot_5](https://github.com/drawpile/Drawpile/assets/51433534/5a4c7b9e-2043-43ac-a0e3-f0b62e4ade28)

Update: The Dock is also doing the same in the Continuous update.

**Comment by askmeaboutlo0m** [comment] 2023-07-08 16:45
This was a bug, it didn't take notice of the chat size changing in some cases. Should be fixed in the continuous release, thanks for reporting it! If the issue persists, feel free to reopen the ticket.

**Comment by vipperz** [comment] 2023-07-12 04:10
It's still happening in the continuous release. Might have reverted with the new Host/Join/Browse addition. Didn't check the previous release, to be honest.

**Comment by askmeaboutlo0m** [comment] 2023-07-12 04:14
Hmm, I can't reproduce this on my side. Maybe a Windows issue, will take a look when I get time to boot into it and wait a few hours for the piled-up updates to install.

**Comment by vipperz** [comment] 2023-07-12 04:21
Oop, deleted my comment on accident, but no rush. Thank you for the time on the issue.

**Comment by askmeaboutlo0m** [comment] 2023-07-13 04:02
I think this might have been related to a problem with windows not immediately restoring to the correct size on Windows. Is this fixed on the current continuous release now?

**Comment by vipperz** [comment] 2023-07-13 09:32
It doesn't seem I'm able to download it. There's only the Source Code being shown.

**Comment by askmeaboutlo0m** [comment] 2023-07-13 10:06
Looks like GitHub Actions goofed up yesterday. I re-ran it and it's available again.

**Comment by vipperz** [comment] 2023-07-13 10:17
Appreciate it. I've exited out of it about 5 times and it does appear fixed now. Thank you so much for your work!

**Comment by askmeaboutlo0m** [comment] 2023-07-13 10:18
Great! Glad it's working now, thanks for reporting it.

**Closed by askmeaboutlo0m** 2023-07-13 10:18 UTC
Labels: Bug
