### ISSUE TITLE
Cursor stuck at the start of pen stroke

### ISSUE THREAD

**Issue by BagelTheBagel** [drawpile/Drawpile#238] opened 2015-08-12 02:13 UTC
1.0.1 on a Microsoft Surface Pro 1. The cursor gets stuck at the start of a pen stroke, making curved lines difficult:
![](http://i.imgur.com/hjZobgt.png)
I tried without bug workaround (Which had the same issue along with jagged lines) and with it. This is the only program on my computer with this cursor problem.

**Comment by callaa** [comment] 2015-08-12 15:10
By cursor getting stuck, do you mean the cursor outline? Does it eventually start moving, does it remain in place for the entire stroke? (In this case, a workaround until I can come up with a real fix is to enable the crosshair cursor so you can at least see some cursor movement.)

**Comment by BagelTheBagel** [comment] 2015-08-12 17:21
The cursor moves eventually, it's just stuck at the beginning of the stroke which causes the sharp corners in those circles.

**Comment by Cockhole** [comment] 2015-08-18 18:41
Happens also on Surface Pro 2 (Windows 8.1) with latest Wacom drivers.
Having [flicks](https://msdn.microsoft.com/en-us/library/windows/desktop/ms694980%28v=vs.85%29.aspx) enabled significantly worsens this issue.
I'm not able to reproduce it currently, but it might be worth noting that the application sometimes crashes entirely on the "up" flick.

**Comment by callaa** [comment] 2015-08-26 11:18
I now managed to reproduce the problem myself too. Turning off the navigation flicks removed the delay for me. I think what's happening, is that Windows is buffering the initial pen movements to determine whether the it's going to be a flick or not. I noticed that Krita, which uses its own tablet event handling code rather than plain Qt tablet events, doesn't have this problem, so the problem is in the way tablet events are handled in Drawpile or Qt. This problem will probably be fixed once either Qt improves its tablet event code or I find an alternative library for cross platform tablet event handling.

**Comment by BaronVonJimmy** [comment] 2016-09-22 21:41
I can confirm I get this on a Surface Pro 2, Windows 10 Pro (Anniversary Update (2016)). Turning off flicks seems to reduce it, but it's still there. I've tried turning off all other sorts of things, the ripple effect, touch controls, toggling the "bug workarounds" option, but none of these have any effect.

**Comment by callaa** [comment] 2018-02-14 15:35
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Comment by BaronVonJimmy** [comment] 2018-02-25 11:45
Any chance of re-opening this?

I just tried 2.0.9 with Windows Ink enabled, and the behaviour is exactly the same.

Windows 10 (Fall 2017 Creators Update), Surface Pro 2.

**Comment by callaa** [comment] 2018-02-25 11:48
Version 2.0.9 now uses the same Wintab and Ink event handler as Krita. Can you try if Krita has the same problem as well?

**Comment by BaronVonJimmy** [comment] 2018-02-25 11:59
Hi there,
Just tried Kritia 3.3.3. No cursor sticking occurs there, in both Wintab and Windows Ink modes.

**Comment by BaronVonJimmy** [comment] 2018-02-25 12:03
Hi again,
Further to this, I've found the following settings has stopped the sticking:
'Windows Ink' ON
'Enable Bug Workarounds' OFF

**Comment by callaa** [comment] 2018-02-25 12:06
So this issue is resolved?

**Comment by BaronVonJimmy** [comment] 2018-02-25 12:09
I would say so, perhaps with the suggestion of text/tooltip on "Enable Bug Workarounds" that things might work better with it off.

**Comment by callaa** [comment] 2018-02-25 12:11
Great! Well, I did suggest turning it off in the release announcement, since naturally a workaround has downsides and thus should only be used if necessary.

**Closed by callaa** 2018-02-25 12:11 UTC
Labels: Tablet
