### ISSUE TITLE
indirect drawing pen pressure opacity

### ISSUE THREAD

**Issue by zeromang** [drawpile/Drawpile#286] opened 2016-01-10 03:43 UTC
indirect drawing is still incremental for pen pressure opacity which makes it hard to paint like most people do in photoshop/krita/gimp

here's an example from drawpile 
http://i.imgur.com/li3uzE4.png

and here is from krita with what should be very similar settings
http://i.imgur.com/DbXMaWC.png (fixed link... oops)
this is the way it works in almost every other program i have ever used

**Comment by callaa** [comment] 2016-01-11 15:59
I found this blog post explaining how the problem is solved in Krita: https://blogs.kde.org/2006/09/22/krita-16-tablets-and-drawing

The trick seems to be to use the "alpha darken" blend mode when painting onto the temporary canvas. Since this change will only affect the rendering engine and not the protocol itself, I can implement it in the next (1.0.3) version.

**Comment by zeromang** [comment] 2016-08-07 09:10
is this being worked on still?

**Comment by callaa** [comment] 2016-08-07 09:29
Sorry, I haven't got it working yet, but I'm still planning on implementing it.

**Comment by Wade821** [comment] 2019-11-28 19:37
I can't find the exact information as to when precisely this was fixed, but I tested it in Drawpile 2.1.14 and it works as expected. Given this was a 2.0.0 milestone, I'm closing this issue. Please feel free to comment if you think it's still an issue.

**Comment by acc4github** [comment] 2021-01-14 01:13
Hey, I tried to use Drawpile (2.1.17) and ran into this issue. It seems that default behavior is 'Derect Drawing Mode' and disabling/unchecking the button does nothing. Is this really fixed?

**Comment by askmeaboutlo0m** [comment] 2023-03-23 13:16
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been fixed in earnest and will be coming in Drawpile 2.2.

**Closed by askmeaboutlo0m** 2023-03-23 13:16 UTC
Labels: Bug
