### ISSUE TITLE
Pressure working on only half the screen

### ISSUE THREAD

**Issue by Waloumi** [drawpile/Drawpile#677] opened 2019-01-03 11:53 UTC
Probably a very rare issue... but just gonna post this in case someone find a fix.

i'm using an intuos pro large

**Comment by tincancrab** [comment] 2019-01-04 23:54
Sounds like you got dual screens. I couldnt find a solution for this. It resolved itself somehow.The way i worked around it was disconnecting the secondary monitor.

**Comment by psicro** [comment] 2019-05-31 02:49
I have this issue right now actually and have been trying to find a solution for months after missing how good this program has been to me for years til now

![image](https://user-images.githubusercontent.com/51220709/58678125-a3b72800-832c-11e9-9073-fd9a5d398ff5.png)

![image](https://user-images.githubusercontent.com/51220709/58678248-027ca180-832d-11e9-8d42-3a5aac307f75.png)

at first i thought it might've been the dual monitor thing, but it's been over a year since i used a second monitor, had had it removed, and still I get this on my screen. 

It even does it when the drawpile window itself is not fully maximized:

![image](https://user-images.githubusercontent.com/51220709/58678293-28a24180-832d-11e9-8491-220b40dcee35.png)

please help me

**Comment by notfood** [comment] 2019-12-25 22:40
Duplicate of https://github.com/drawpile/Drawpile/issues/643

It appears to have been fixed with the tablet handling overhaul. Re-open #643 if you're still having the issue.

**Closed by notfood** 2019-12-25 22:40 UTC
