### ISSUE TITLE
Reset removes session permissions

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#557] opened 2018-01-28 21:58 UTC
Getting multiple instances of users complaining that locked layers (i haven't tested default layer yet), as well as the permissions in session settings, are all removed when a reset occurs. (Currently running 2.0.6 server side)

**Comment by tincancrab** [comment] 2018-01-28 22:21
Apparently this is occurring on 2.0.5.1 as well. No idea if this is happening on newer clients only.

**Comment by callaa** [comment] 2018-01-29 16:23
Does this happen with automatic session resets or just manual ones? Autoresets should include layer lock and other info, but manual resets currently do not. (There is a technical reason for this, but it should be possible to fix.)

**Comment by tincancrab** [comment] 2018-01-29 21:53
They say it happens on both. In the largest session on my server, auto-reset fails in their session after awhile and has to be done manually, so a workaround would be good. (I'm not surprised it breaks, since theres 35+ users in a session thats up for days)

**Comment by callaa** [comment] 2018-01-29 22:07
Okay, now I found the problem. The new version indeed does not add the access control data to the reset snapshot. I think I'll rewrite that part so the data will get included when resetting manually as well.

**Comment by Lahtirus** [comment] 2018-01-29 22:35
The problem is on both auto-reset and manual. After the auto-reset stopped working the room been doing manual resets. The locked features and layer locks all gets wiped out.

**Comment by callaa** [comment] 2018-01-30 16:30
@Lahtirus by "after the auto-reset stopped working", do you mean the entire feature stopped working or just the permissions part?

**Comment by tincancrab** [comment] 2018-01-30 17:42
They mean the entire feature. Auto-resets would just quit. Resets would have to be done manually until a rehost.

**Comment by callaa** [comment] 2018-01-30 17:54
Do the autoresets fail or just stop happening? Is there anything in the log file about the reset failing?

**Comment by tincancrab** [comment] 2018-01-31 02:37
They just stop happening. Theres no error as far as I know beyond saying the session has low memory (the usual before a reset happens). I'll look through the logfile to be sure

**Comment by Lahtirus** [comment] 2018-02-04 06:03
Also for some reason, people can't draw with a mouse.

**Comment by callaa** [comment] 2018-02-04 08:16
@Lahtirus Is this problem triggered by the reset?

**Comment by tincancrab** [comment] 2018-02-09 10:21
No clue, asking lahiti, but adding in here a related question. How do we prevent users who dont upgrade from renaming and creating layers upon reset? Common issue right now. I've noticed that this is a client side problem: I am currently running a 2.0.5 server and a 2.0.6 one, and this issue happens on both, and apeared with 2.0.6. It makes these builds possibly tools for malicious people to ruin a room?

**Comment by tincancrab** [comment] 2018-02-09 10:22
*When the next build with the fix is officially compiled and released.

**Comment by callaa** [comment] 2018-02-10 07:35
The fixed version adds the permission bits to the reset image like version 2.0.4 (with the addition that manual resets now add all the permissions too,) so there shouldn't be an opening where users could make changes they're not allowed to. The UI becomes unlocked during the reset, but no actual changes can be made, since the original permissions will be reactivated before the reset ends and any new user commands are processed.

**Comment by callaa** [comment] 2018-02-14 15:23
The new version is now out and this bug should be fixed now.

**Closed by callaa** 2018-02-14 15:23 UTC
