### ISSUE TITLE
I can't join or host any sessions. "SSL Handshake Failed"

### ISSUE THREAD

**Issue by Pandikko** [drawpile/Drawpile#523] opened 2017-10-28 13:16 UTC
I can't join or host any sessions. I hosted one a couple days ago that ended up having no one join so there was nothing drawn. Ever since that one, I keep getting and error that says "Network error: SSL handshake failed @ https://drawpile.net/api/listing/" What does that mean and how do I fix it?

**Comment by weylin6** [comment] 2017-10-28 15:26
I'm getting a SSL Handshake Failed, too.
Also, when I tried to go to the main website, Chrome says the connection is NOT secure, that the certificate is out of date, and it stops me right there.

**Comment by Pandikko** [comment] 2017-10-29 00:19
I got that too! I just told my browser to trust it and I got to the site. I wish the handshake thing worked as well.

**Comment by callaa** [comment] 2018-01-07 14:33
A bit late, but this was probably caused by the certificate auto-update script not working. It should be fixed properly now (I hope.)

**Closed by callaa** 2018-01-07 14:33 UTC
