### ISSUE TITLE
Severe lag creating weird lines

### ISSUE THREAD

**Issue by spartan8ter** [drawpile/Drawpile#321] opened 2016-04-14 07:23 UTC
![image](https://cloud.githubusercontent.com/assets/9081712/14519931/5367b678-0254-11e6-9b2d-fbe2304d9c60.png)

Drawpile seems to be lagging for me. The mouse seems to jump every few seconds which is creating these annoying lines. I do believe it is not my tablet's problem as the pressure works fine.

If needed, I may need help using the QtTabletTest program or something, I have no idea how to use it.

I'm using a Intuos 5 Wacom Tablet.

**Comment by Wade821** [comment] 2019-11-28 22:32
Closing issue, duplicate of #179 it seems to me. Please feel free to comment there! 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Closed by Wade821** 2019-11-28 22:32 UTC
