### ISSUE TITLE
Rotate Selection (ALT+DRAG) doesn't works.

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#380] opened 2016-12-11 12:03 UTC
_Windows 8.1 64 bits
DrawPile 1.0.5_

NOTES: In earlier versions the rotation of a selected area worked properly
https://github.com/callaa/Drawpile/issues/245

-The **ALT+DRAG** action of a selection does not trigger rotation.

**Comment by callaa** [comment] 2016-12-12 18:45
I was unable to reproduce  the issue. If you're using a tablet, try enabling the bug workaround mode in the preferences dialog.

**Comment by erik90mx** [comment] 2016-12-12 19:30
To test the rotation, I'm using the mouse, the result is the same with the bug workaround enamble.

**Comment by callaa** [comment] 2016-12-13 16:11
Are you dragging from inside the selection or outside?

**Comment by pachuco** [comment] 2017-01-10 02:04
I had confusion with rotation, where I tried to drag by the handles of selection instead of the interior.

**Comment by Wade821** [comment] 2019-11-20 06:18
Rotation mode changed in Drawpile 2.1.12 to be more discoverable. Closing issue.
https://drawpile.net/news/release-2.1.12/

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Closed by Wade821** 2019-11-20 06:18 UTC
