### ISSUE TITLE
Eraser isn't working

### ISSUE THREAD

**Issue by butterybutt** [drawpile/Drawpile#343] opened 2016-07-17 02:52 UTC
I use a cintiq 13hd to draw, but when I switch from my pen to the eraser on my tablet pen, the eraser won't change to the eraser tool and keeps using the pen tool. I'm sorry for my bad english but I'm trying to figure out on how would I fix this.

**Comment by shadamy22** [comment] 2016-07-17 17:55
I have an Intuos 4 and I have the same issue. It worked perfectly before, but now with the new update, it doesn't function the same.

**Comment by tincancrab** [comment] 2016-12-29 16:30
Would also like to hop in and say I have this same issue, where it will detect the eraser end of the tablet pen once and do the appropriate action to change the tool to eraser, but then quits detecting it after that point until a restart. Checking bug workarounds box in tablet preferences in Drawpile doesn't fix it. There's at least a few others I've spoken to have had this issue as well and won't upgrade past 1.0.2 because of the bug appearing in later builds.

**Comment by wamserma** [comment] 2017-02-07 20:38
Duplicate of #341 ;)

**Comment by callaa** [comment] 2018-02-14 15:34
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Closed by callaa** 2018-02-14 15:34 UTC
Labels: Tablet
