### ISSUE TITLE
Drawpile Keeps Crashing [bug]

### ISSUE THREAD

**Issue by drawtink** [drawpile/Drawpile#919] opened 2020-08-02 05:00 UTC
Hi there, 

Earlier I attempted to host a session and connected to "this computer", tried to resize the canvas and it crashed. Now, whenever I open the application, it immediately crashes and I cannot do anything. I tried uninstalling/reinstalling, and restarting my pc, neither worked. What should I do to fix this? 

Thank you

Edit: I am running Windows 10 and I have the latest version of Drawpile installed.

**Comment by Wade821** [comment] 2020-08-02 05:48
Unlikely it's a bug given most people can resize without crashing. For it to be a bug, it has to be reproducible among many users. Given there's a number of factors at play it might have to do with something else actually, so before we label it a bug, let's try some things first. 

And by latest version of Drawpile, that would be 2.1.7 right? When you attempted to resize the canvas, did you attempt to make it something ridiculously large? Alternatively, you could try opening an image with Drawpile by right clicking an image, select open with, and choose Drawpile or select "Choose another app" instead to see if the option appears there. You may have to browse to your installation of Drawpile. This may give you a small enough of a canvas to use to pick something else that won't bug it out. 

Also, this might seem unrelated... but have you tried opening Drawpile when your computer is offline by any chance? There's occasionally issues that have come up with version checks causing it to crash because of code injection/alteration by your ISP. In these cases, checking "Don't check automatically" found under Help, Check for Updates was able to resolve the issue. 

Are you using the 32 or 64 bit version of Drawpile? To answer that if you don't know off hand, I need to know two things. First off, whether your computer is 32 or 64 bit. Once you know that info, the second link below should help you figure out what version of Drawpile you are using. 

https://cdn.discordapp.com/attachments/546260997703467009/588883724758941706/unknown.png

https://cdn.discordapp.com/attachments/546260997703467009/588883861283405873/unknown.png

Also, there's an official Drawpile Discord server for more immediate help. Invite link on Drawpile.net in the bottom left corner.

**Comment by Wade821** [comment] 2020-08-02 06:11
Resolved with opening an alternate image, to pick a smaller canvas size.

**Closed by Wade821** 2020-08-02 06:11 UTC
Labels: Support
