### ISSUE TITLE
Crash when hosting server after dprec playback

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#313] opened 2016-03-30 09:59 UTC
Steps to reproduce:
1. Host server(I used dedicated).
2. play back .dprec file.
3. Host a session on said server.
4. Crash.

Workaround: Export that playback to .ora, open it, then host session.
I did not try this with built-in server.

**Comment by callaa** [comment] 2016-03-30 18:25
Does this happen with all recordings or just some? (For example, does it happen with short recordings, or is there anything more specific that triggers the bug?)

**Comment by pachuco** [comment] 2016-03-30 18:54
Actually, I am having trouble producing consistent results.
Also, the crashing is more of program quitting itself. No error message, no nothing.

**Comment by pachuco** [comment] 2016-03-30 19:05
If it helps, I obtain my recordings after dedicated server shutdown. They are typically named blabla.dprec.abxxxx
I rename them to .dprec and load them in drawpile.

Although, I now seem unable to reproduce this consistently.

**Comment by pachuco** [comment] 2016-03-30 19:38
Sir, I think [the bug] it's laughing at us.

**Comment by callaa** [comment] 2016-03-30 19:46
Probably a memory corruption bug, like a bad pointer dereference. These bugs typically are difficult to reproduce exactly. I'll try running Drawpile in valgrind and load a big recording. That should help locate the problem. (It's also possible that the bug isn't present on all platforms. I develop primarily on a 64bit Linux platform, while the windows version is 32bit.)

**Comment by pachuco** [comment] 2016-03-30 19:52
if it helps, I have *cough* WinXP x86 SP3 *cough*

**Comment by pachuco** [comment] 2016-03-30 21:05
Dedicated server logs for crashes go here:
[2016-03-31T00:03:15 INFO] #1 [xxx.xxx.xxx.xxx] Username@159d0dbb-9106-404b-95a5-8
3032206ae26: Joined session
[2016-03-31T00:03:15 INFO] Session 159d0dbb-9106-404b-95a5-83032206ae26: Closing
 non-persistent session
[2016-03-31T00:03:15 INFO] Session 159d0dbb-9106-404b-95a5-83032206ae26: History
 size was 37 bytes
----------------------------------------------------------------------

**Comment by pachuco** [comment] 2016-03-30 21:45
Got a crash with built-in server.

**Comment by pachuco** [comment] 2016-03-30 21:48
Again, saving to .ora and opening that for hosting has provided relief.

**Comment by Wade821** [comment] 2019-11-28 22:10
I'm not sure that this should be considered a bug, since as you said yourself in #283  that you use "winapi wrapping to use Drawpile in XP." Furthermore, I'm unable to replicate your particular issue. I tried using the built in server and an external server. I loaded up a DPREC and hosted just fine with no crashing. 

Is this still happening for you? I think we'd be better off closing this issue since it's an unsupported platform, so this is out of scope. 

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by Wade821** [comment] 2019-11-29 00:28
Closing issue since Windows XP is no longer supported.

**Closed by Wade821** 2019-11-29 00:28 UTC
Labels: Bug
