### ISSUE TITLE
Expanding or feathering or shrinking small selection jams shortcuts

### ISSUE THREAD

**Issue by incoheart** [drawpile/Drawpile#1379] opened 2024-10-08 03:23 UTC
If I make a small selection and feather or expand it, I can no longer alternate between the brush and the selection tool via shortcuts, nor deselect. It seems all the shortcuts become jammed.  It only happens with small selections. If the small selection is expanded by a significant area, like 20 pixels, this bug will not happen, so I theorize the bug has to do with the small size of the selection as it pertains to its freshly modified bounds.

The way to replicate this is to 

1. make a small selection with the lasso 
2. make an adjustment within a pixel range that keeps the area small via **Expand/Shrink/Feather Selection**  (menu or shortcut both trigger the bug) 
3. try to undo, deselelect, switch brush, etc via shortcut but the tool will be stuck on the lasso until intervening by deselecting in the menu (_not_ by double clicking outside nor the assigned shortcut) or moving the window (I'm in X11 / Openbox / LXQt, and moving the window by clicking and dragging while holding down Alt achieves this as well as minimizing  then maximizing the window)

This is a 1200x1200 canvas. The first screenshot is a tiny selection that can easily trigger this bug with a modification of 2 pixels. 20 pixels expansion of this shape will not trigger this bug. 
![bug_01](https://github.com/user-attachments/assets/21e22b1f-4718-42f1-86b8-14b579e9248f)

The second screenshot is a large selection that I shaped like a heart that, comparatively, did _not_ trigger this bug.
![bug_02](https://github.com/user-attachments/assets/654348ff-add1-438f-85de-7bc8764e0d1a)

**Comment by incoheart** [comment] 2024-10-08 03:29
Um, I'm not sure if this is a good bug report because it's not happening with the aAppImage. I built Drawpile from source only today.  I was convinced the building from source had identical behavior as the appimage. I just checked the AppImage after posting and it isn't doing it yet. I'll keep testing the selection tool.

**Comment by askmeaboutlo0m** [comment] 2024-10-08 11:51
It sounds like an issue where something is capturing your keyboard input maybe? And building from source may end up linking against Qt6, whereas the AppImage is Qt5, so they may have different behaviors in that regard.

**Comment by askmeaboutlo0m** [comment] 2024-10-09 00:46
I really don't know why this would be happening, it's pretty inexplicable. I can't reproduce it on Arch with Qt6 under X11 anyway, but that's a very different system from Fedora that probably uses Wayland and a different Qt version with a different set of patches.

But Qt6 is generally more buggy than Qt5 still, it has trouble with tablet cursors and even some crashing bugs. So I'd say it makes sense to stick with Qt5 for now on your end and close this issue in the hopes that upstream will end up fixing whatever causes this and the issue ends up disappearing on its own.

**Closed** 2024-10-09 00:52 UTC
Labels: bug
