### ISSUE TITLE
Floating docks don't restore properly on application startup

### ISSUE THREAD

**Issue by SnazComic** [drawpile/Drawpile#1125] opened 2023-08-04 14:26 UTC
Have tried redownloading but did not fix issue

**Comment by SnazComic** [comment] 2023-08-04 18:36
![image](https://github.com/drawpile/Drawpile/assets/141430236/010751e4-5dbc-442b-b36d-b81c832d2049)
![image](https://github.com/drawpile/Drawpile/assets/141430236/e30db934-63df-482e-b7f4-1de2414ed198)
![image](https://github.com/drawpile/Drawpile/assets/141430236/d77f3b8e-b9a1-4608-aebc-75dfcbf88128)
I'm on windows!

No matter what I do I can't get the navigator open

**Comment by SnazComic** [comment] 2023-08-04 20:50
Oh- It seems to work now- I'm not sure what happened but it suddenly appeared! Thank you and sorry for bothering!
![image](https://github.com/drawpile/Drawpile/assets/141430236/aa7fa2d8-948a-4613-ae8a-e71d4d2467fe)

**Comment by SnazComic** [comment] 2023-08-04 20:53
oh wait I closed dp and reopened and its gone again OTL

**Comment by Wade821** [comment] 2023-08-04 21:06
Personally, I'd say you should join the Discord server, invite link is on the lower left corner of the Drawpile website. Can usually get faster responses there.

But I think this is actually a bug. I was able to reproduce it by simply not having the Navigator docked. After closing Drawpile, this behavior shows up. Loading up a pre-set layout seems to fix it. I wonder if it's because the drawpile.ini file doesn't seem to be given coordinates to read from later in that file?

For now, leave it docked @SnazComic until a fix can be made.

**Comment by askmeaboutlo0m** [comment] 2023-08-05 04:20
Yup, also happens on Linux and is related to floating docks.

**Closed** 2023-08-05 04:46 UTC
Labels: Bug

**Comment by askmeaboutlo0m** [comment] 2023-08-05 05:01
I think I fixed it now, thanks for reporting it! The fix is available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Does this resolve the issue? If not, feel free to re-open the ticket.

Techy explanation what was happening here: there was a different bugfix to stop docks from changing their size when you start the program, which involves disabling the window until it's fully ready. For some reason that disabled state gets passed onto floating docks, but then they don't get automatically re-enabled along with the main window, leaving them forever stuck disabled. Now Drawpile re-enables every window it can get its hands on, rather than just the main one.
