### ISSUE TITLE
Exporting Video?

### ISSUE THREAD

**Issue by Rockmanan** [drawpile/Drawpile#374] opened 2016-11-17 09:59 UTC
Hi! I love the program, but I'm having a few issues when trying to export recordings.

When I try to export, the program crashes soon after, to the point of being impossible to export all but a few seconds of a recording.
- I've tried exporting both as image & video, as well as exporting at lowest fps and pixel setting, with no improvement. Crashing happens literally every time I try exporting, but the time it takes to crash seems arbitrary. Sometimes it will allow for a decent amount of export before crashing (the longest which exported nearly an hour of feed), but mostly exporting will crash Drawpile within a few minutes or seconds of starting.  

The crash is my main issue, but while trying to navigate the recording features, I found a few notable inconveniences & have some suggestions:
- Resizing the canvas to a smaller size seems like it would help the crashing, but cannot be used for many recordings.  Either the resize canvas tool is too limited, or I can't find documentation on the correct way to use it.  Canvas resize appears to only allow cropping from the bottom or left. If the section of the canvas I want to keep is not in the top or the right, resize will crop it. I also tried offsetting before resizing, but on export, the recorded strokes played without the offset, and the drawings stayed in their original positions, hitting my remaining canvas randomly or not at all. If the resize feature is functioning correctly, I'd like to suggest adding an anchor to the canvas resize as Photoshop does, allowing the user to change the anchor point of the crop- https://i.gyazo.com/95533d49c6b90a24859327fcad8c5d69.png or else adding a marquee crop tool.
- Navigating through indexed recordings is fairly unwieldy. With longer streams, it is difficult to find the desired section, which is understandable. However, requiring a double click instead of single to navigate can combine with lag to become very unresponsive & frustrating. 
- Being able to see a ruler at the bottom of the indexed feed, possibly in percentages, would be very helpful, particularly if the recording isn't marked out. For example, once you find that you started drawing at 22.22% into the feed, navigating back to that point would be far more simple than the existing indexed feed. It could also help users keep track of how far an export has progressed. Seeing markers along this ruler would also be very helpful.
- Is there a way to cut out segments of a recording, not simply the actions within it? For example, while exporting a recording from a public server session, if the first 20 minutes of the feed were unwanted, is it possible to cut out that 20min section entirely to make the recording shorter to play through and index, & generally easier to handle? In the same vein, is it possible for a users to split & save the recording into pieces for easier export, either by deleting segments or splitting by marker? (i.e. saving a 4 hour recording into four different files, each a 1 hour segment)? If it is already possible, I would request that the feature & process be made clear somewhere on the main Drawpile site. If not, I would like to suggest this feature.
-Would it be possible to add a setting that automatically adds a marker when a user that is recording joins a session?

Thank you for reading!

**Comment by callaa** [comment] 2016-12-11 10:52
Hi, and sorry for the late reply.
Are you using the Windows version? Unlike the official OSX and Linux builds, the current Windows version is built for 32 bits, which might cause it to run out of memory if the canvas is very large. If possible, try exporting the video on a Linux or a Mac computer to see if it makes any difference.

Suggestions:

> Resizing:

Resizing the canvas is an action that is added to the event log and does not affect the past events. Currently, there is now way to crop the exported video (except in post production), but the target frame size can be set in the export dialog.

The canvas resize anchor is a good idea, and something I've been meaning to do, just haven't gotten around to it yet.

> Ruler

Have you tried the 2.0 beta version? It has a new thumbnail based index that is much easier to navigate.

> Cutting sections

There is no tool to mark certain sections for cutting, but it can be done manually. You can simply skip to the desired point on the timeline and the video export from there. You can also pause the playback and skip ahead (or behind) can continue again.

> Splitting

Splitting an existing recording is not currently implemented. Splitting a recording requires the same amount of time as generating the index, since the event log must be played back to generate the starting points for the splits.
You can, however, get pre-split recordings from the server. If you run your own server, enable serverside recording and set a session size limit. The server will then split the recording every time the size limit is reached.

> User markers

It is possible to implement a feature that adds a marker whenever a user joins, however other users (or the server) cannot tell if a specific user is recording or not.

**Comment by Wade821** [comment] 2019-11-29 07:43
Closing issue, duplicate of #248. Please comment there for further discussion.

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Closed by Wade821** 2019-11-29 07:43 UTC
