### ISSUE TITLE
using ctrl to color pick doesn't work on android, the save option crashes the app [Android/HarmonyOS]

### ISSUE THREAD

**Issue by ariqhadiyan** [drawpile/Drawpile#1164] opened 2023-11-20 07:16 UTC
Like the title said, some keyboard shortcut like color picker doesn't work on android (I am using an external keyboard with my tabet), even when I changed the shortcut to something else. most shortcuts also require mouse, which normally isn't a thing to be used with android phone and tablet.

the other thing is that I can use the 'save as' option to save into a new file just fine, but the normal 'save' function will immediately crash the application every time I use it.

**Comment by askmeaboutlo0m** [comment] 2023-11-20 19:33
Yeah, looks like modifier keys don't get reported properly on Android. Hitting the Shift key also gets the title bars of docks stuck invisible until you press another key. I fixed those now by looking at the modifier keys manually, it's available in the continuous release again: https://github.com/drawpile/Drawpile/releases/tag/continuous

You can attach a mouse to an Android device just fine, it's very common to have on a Chromebook for instance.

Save crashing the application is not something I can reproduce on any of the devices I have access to. How does the crash manifest exactly? Specifically:
* Does it tell you "this application has stopped" or similar, or does it just close?
* Does it crash when you save for the first time? Like, starting Drawpile and just saving the blank canvas immediately.
* Does it crash if you use Save As and then Save again afterwards or does it only happen if you open a file and try to save it again?
* Do only specific file formats crash or is it all of them?
* Does it only happen in specific folders? Some pre-existing folders on Android are special, such as Downloads or Pictures, and may have weird restrictions what you can do in them. The SD card and internal storage may also act differently.

**Comment by askmeaboutlo0m** [comment] 2023-11-22 02:48
Hmm, okay, so it looks like it crashes only for ORA files that Drawpile didn't save.

Further narrowing it down, does it also happen when you open an ORA file you saved with Drawpile in a previous session or is it only ORA files from other sources? Like, open Drawpile, save an ORA file, close the program, open it again, open the file again and try to save it.

And do PSD files behave the same as ORA files or do they work properly?

**Comment by askmeaboutlo0m** [comment] 2023-11-22 15:19
Yeah, Android file permissions are very strange. It may be that FreeFileSync is somehow marking the files in a special way. Or it could be because Drawpile is built to support very old Android versions, where the permission system used to be different, so that might cause some kind of incompatibility.

It's probably something you can contact the authors of FreeFileSync about though! It looks like they have a forum on their website, maybe they know what could cause the issue. You can point them to this issue and if the developer wants to contact me, they can either do it here, Discord or IRC, as listed on <https://drawpile.net/help/>

I'll close this issue for now, since I don't think there's anything to do on Drawpile's side, but feel free to post here if you manage to solve the issue or get more information. And thanks for reporting these issues!

**Closed by askmeaboutlo0m** 2023-11-22 15:19 UTC
Labels: Bug, Platform issue, Needs info
