### ISSUE TITLE
Line glitch?

### ISSUE THREAD

**Issue by berry-loop** [drawpile/Drawpile#765] opened 2019-05-25 11:38 UTC
![Capture](https://user-images.githubusercontent.com/51021463/58368560-8b43a980-7ef7-11e9-92d9-a7aeb09457a8.PNG)
Hello!
I have recently updated drawpile from 2.0.9 (or something close, I don't remember that well?) to the latest version and noticed that it started to "straighten" lines at the start. The faster i draw the line, the bigger is the straight part. It is a recent issue so I don't think it is something with my tablet or pc nor has it happened in csp (clip studio paint).

This issues seems to also happen in this thread: https://github.com/drawpile/Drawpile/issues/729
If anyone can help it will be really appreciated!!

**Comment by callaa** [comment] 2019-05-25 14:42
Try enabling (or disabling) Windows Ink mode from the settings dialog. As far as I can tell, this problem is caused by the operating system intercepting the beginning of each stroke while it's trying to decide whether it's a gesture or not.

**Comment by berry-loop** [comment] 2019-05-25 16:32
@callaa I can't find how to disable it? I looked up tutorials but they don't seem to work for me.

**Comment by berry-loop** [comment] 2019-05-25 18:12
update: disabled it, still doesn't work :-(

**Comment by callaa** [comment] 2019-05-25 20:22
Have you ever used Krita? Does the same problem happen there? (I ask because I'm using Krita's tablet event handling code. If it works there, there must be something more I could copy.)

**Comment by berry-loop** [comment] 2019-05-26 12:39
It seems to also happen in krita

**Comment by Wade821** [comment] 2019-06-17 07:29
When you disabled Windows Ink, did you do this in just Drawpile? Or did you do it in your tablet driver settings (assuming wacom here)?

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings.

**Comment by Wade821** [comment] 2019-11-28 20:55
Please let us know if this is still an ongoing issue. 

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by Wade821** [comment] 2019-11-28 20:58
I'm going to go ahead and close this issue since it's a duplicate of the problem you mentioned in your first post. trying to go through and clean up repeat issues.

**Closed by Wade821** 2019-11-28 20:58 UTC
Labels: Support
