### ISSUE TITLE
Can't get pen dock to lock to the side.

### ISSUE THREAD

**Issue by djblend070** [drawpile/Drawpile#325] opened 2016-04-30 04:49 UTC
So you know how you can hide or show different docks, and how you can move them to your liking? Well I can move every dock except for the one with the pen settings, the one where you can choose opacity settings, different brushes, and more. I'm kinda new to Drawpile so I'm not sure if I'm just being stupid. Could someone instruct me on how to get the problematic dock to lock onto the side?

**Comment by AoAlea** [comment] 2016-05-12 02:45
Yeah I had this problem too
the docks usually have a close and undock button (with a window and an x) 
but the pen dock doesn't have one

How I solved this: reset the user interface, uncheck all of the docks in View -> Docs
then join a new session 
the new session should have all the default settings again

**Comment by AoAlea** [comment] 2016-05-12 04:35
Workaround: 
1. Hide the pen dock with View>Docks>1.[current tool]
2. Join a new session and close the old window

**Comment by djblend070** [comment] 2016-05-23 20:20
Thank you! I'll give it a shot!

**Comment by djblend070** [comment] 2016-05-23 20:26
Did not work, unless I somehow fudged it up.

**Comment by 150mm** [comment] 2016-05-24 14:57
I'm also having an issue with this.
I'm running the program on Windows 10, and have tried uninstalling/reinstalling, rebooting my PC, openinga nd closing the program, uninstalling, then rebooting, then installing, as well as trying to delete registry values; my brush panel has no (x) button above it, and sits on top; I can't move or drag it, but I can 'resize' it around by dragging the corners of the box. This is incredibly frustrating.

**Comment by djblend070** [comment] 2016-05-31 23:24
Yeah. They really need to fix this problem. I still can't use it and it
sucks cause me and my friends can't really collab anymore.

**Comment by callaa** [comment] 2016-06-01 13:09
Sorry I haven't responded sooner. I can't reproduce this problem myself. If you drag the dock by the header (the tab bar) near the edge of the window, it should return to its place. Is the dragging functionality itself broken?

**Comment by djblend070** [comment] 2016-06-03 14:52
The dragging functionality itself is indeed broken. It will only let me
make the windows bigger or smaller, though it is still stuck in one place.
If needed I can use a screen recorder and upload the recording to Youtube
this weekend. So you can see the problem for yourself.

**Comment by callaa** [comment] 2016-07-03 09:23
Version 1.0.3 is now out, which includes an updated Qt version. Does the bug occur in the new version too?

**Comment by vdh** [comment] 2016-08-27 08:04
This is still a problem in 1.0.4, the brush dock has gone off the rails and doesn't have a header or anything any more
![screenshot 2016-08-27 18 03 47](https://cloud.githubusercontent.com/assets/573501/18026119/ad4a0984-6c80-11e6-9679-a10592d5f2b8.png)

**Comment by callaa** [comment] 2016-08-27 08:25
The button/tab bar on top replaces the normal header in this dock to save space. What happens if you try to drag the dock from it?

Also, which OSX version are you using?

**Comment by AoAlea** [comment] 2016-11-20 07:34
Fix: After angrily spam double clicking the detatched dock while in fullscreen, it has returned! 

There must be a small area on the button/tab tool bar that you can double click to return it. Maybe switching between minimize -> window -> fullscreen helped?

**Closed** 2018-02-05 20:13 UTC
