### ISSUE TITLE
Add more stabilizer options or more levels of smoothing

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#933] opened 2020-09-29 07:42 UTC
The current maximum level of Smoothing from Drawpile is just not enough to stabilize my strokes, it makes doing a proper cartoony lineart really hard to do!

Can you add more levels of stabilization to the smoothing? Or override options, or just allow us to pick a custom smoothing level, I really want the stabilizer to have additional levels, at least something closer to Paint Tool Sai S-2 stabilization or the value 30 on Clip Studio's stabilizer setting.

I actually tried to use 3rd party software like Lazy Nezumi and it doesn't work... I think it's just better to implement this feature directly on Drawpile or just updating the Smoothing slider with even more smoothing

**Comment by notfood** [comment] 2020-09-29 17:02
The stabilizer in Drawpile uses very simple math, it depends on two numbers. The `smoothing` slider bar merely increases the number of points in the calculation but what also helps smoothing is changing `spacing`. Try lowering your `spacing` under the brush settings to increase the smoothing levels even more.

**Comment by Charmandrigo** [comment] 2020-09-30 07:11
> The stabilizer in Drawpile uses very simple math, it depends on two numbers. The `smoothing` slider bar merely increases the number of points in the calculation but what also helps smoothing is changing `spacing`. Try lowering your `spacing` under the brush settings to increase the smoothing levels even more.

I already use a brush with as little as 10% spacing and is just not enough 😞 My hand is not too precise, I would appreciate if it can have even more softer strokes, or adding new ways of stabilize

**Comment by askmeaboutlo0m** [comment] 2023-03-24 12:11
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Duplicate of #179, but a valid issue. Partially fixed by MyPaint brushes coming in Drawpile 2.2, since they have a real stabilizer, but still something missing from classic ones, which would be nice to have.

**Closed by askmeaboutlo0m** 2023-03-24 12:11 UTC
Labels: Feature, Usability, Tablet
