### ISSUE TITLE
Drawpile on Steam

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#305] opened 2016-03-27 12:53 UTC
Putting Drawpile on steam to increase it's exposure

**Comment by callaa** [comment] 2016-03-28 11:32
I'm not at all familiar how this is done, but I'll look in to it.

**Comment by blurymind** [comment] 2016-06-29 22:52
It will draw attention and more users. You could also get some funding!

Krita for example became available on steam since last year - and their userbase exploded. The application is open source/free but people still gladly pay for it in order to support the development and also get a convenient way to update it:
http://store.steampowered.com/app/280680/

**Comment by Wade821** [comment] 2019-11-28 20:03
I think this would be a great idea, but it isn't going to work for Callaa as I was reading through it.

https://partner.steamgames.com/steamdirect

I've mentioned it to him, but I think for various legal reasons he probably won't be able to pursue this path.

**Comment by Wade821** [comment] 2019-11-28 21:30
After talking with Callaa on Discord, we don't think it's worth pursuing at this time. I'm not opposed to making it happen, I'd even donate to the cause since there's a $100 publishing fee. But there's also the matter of releasing Drawpile for Steam and dealing with tax paperwork that'd come with doing it.

I'll leave it open for future consideration though since we now have a label for this type of issue.

**Comment by Wade821** [comment] 2020-06-26 04:56
Moderator Channel of the Drawpile Discord. 
11/28/2019 - @callaa 
> Making a release is already quite involved, since I need to make two builds for windows, a mac build, flathub build and the docke build. With steam in the mix, it's three more builds and their release process

He basically said it wasn't worth it, so I'm closing this issue now.

**Closed by Wade821** 2020-06-26 04:56 UTC
Labels: Publicity
