### ISSUE TITLE
cant draw?

### ISSUE THREAD

**Issue by VivaLaVaati** [drawpile/Drawpile#224] opened 2015-08-04 14:26 UTC
i downloaded drawpile yesterday and me and a friend joined a drawpile.net hosted server- that part was fine, but then it started glitching out.

when i would make a new layer it would delete itself (nobody was undoing it or deleting it) so i was like "Okay, just a bug" and made a new server which seemed fine until 10 minutes later when the brushes started flipping out. 

what i mean is, when i tried to click on a layer to draw on and then try to draw, it would not work. nothing would show up and it still wont. i tried resetting everything in preferences and even reinstalling but it wont work on either my mouse or my tablet..

furthermore it started making multiple undo's undo at once and i lost alot of art i already tried to draw...

i attempted joining other servers and even offline but it wont work?? what do

**Comment by callaa** [comment] 2015-08-04 17:55
What is probably happening is that the server is ignoring drawing commands sent by your client. After the client has been out of sync with the server for 60 seconds, it will clear everything in the local buffer. This is most likely what causes the layers and drawings to disappear.

As to why this happens, I'm not sure yet. I'll have to do some investigating. Does this happen even when you host a session with the built-in server with no other people in it?

**Comment by VivaLaVaati** [comment] 2015-08-04 23:51
it happens even when im offline, it happens when i host OR join..

**Comment by callaa** [comment] 2015-08-05 06:12
Can you make a short session recording in offline mode that demonstrates the bug? That would help me narrow down the cause. The fact that it happens in offline mode suggests that the bug is not caused by any random stream corruption (since messages are not serialized in offline mode.)

**Comment by VivaLaVaati** [comment] 2015-08-05 16:06
https://www.youtube.com/watch?v=w3M5-dMw8NI&feature=youtu.be

**Comment by callaa** [comment] 2015-08-06 17:20
Thanks. Can you also send me a .dprec file? Also, one thing to try would be to switch the pressure mode to something other than stylus. If there is some tablet bug that causes each tablet event to have zero pressure, it could explain why nothing gets drawn.

**Comment by VivaLaVaati** [comment] 2015-08-07 01:24
1. everytime i try ot send files it says it fails to send which is why i
had to upload the youtube video, and 2. how do i get a dprec file and what
is it, im sorry, i probably should have read about it somewhere

**Comment by callaa** [comment] 2015-08-07 14:32
Dprec is Drawpile's native recording format. You can start recording via the *Record* item in the File menu. Based on the youtube video, it looks like the pen events are not registering, but I can tell more by analyzing the dprec file.

**Comment by VivaLaVaati** [comment] 2015-08-07 15:28
alright, ill do that now. also, i dont think its the tablet because i tried
drawing with the laptop's built in trackpad/touchpad thing, and a usb mouse
too. again, i figured it was a glitch so i did reinstall it the day it
happened, but it looks to be permanent. also im doing the thing now so ill
send it shortly o.o

**Comment by VivaLaVaati** [comment] 2015-08-07 15:39
so i did get the brush to work again, only after i changed the smooth
settings, but it glitchd out again :s

**Comment by callaa** [comment] 2015-08-07 15:42
I recall someone else had a problem like this too, which was fixed by resetting the settings. (By clicking the reset button in the preferences dialog.)
If you can make the dprec recording I might be able to figure out which setting is responsible.

**Comment by VivaLaVaati** [comment] 2015-08-07 16:30
i thought i sent it?
also i did try resetting everything multiple times but it didnt work.

**Comment by callaa** [comment] 2015-08-07 16:32
Github probably doesn't accept attachments in issue replies. Try sending directly to my email.

**Comment by VivaLaVaati** [comment] 2015-08-07 17:43
hhh this doesnt say whre your email is im dumb

**Comment by callaa** [comment] 2015-08-07 17:53
It's on my user page here: https://github.com/callaa/

**Comment by callaa** [comment] 2015-08-08 08:32
Thanks, now I got the file. Here's a snapshot of somewhere near the middle of the recording:
![vaati-test1](https://cloud.githubusercontent.com/assets/464576/9149698/84c257d8-3dbe-11e5-9755-3d392f51a3c5.png)

It seems that the missing strokes do get recorded and appear in the playback. If you play back the file yourself, will they show up?
However, something weird is indeed going on. There are no UndoPoints for the strokes that did not show up when drawing. Usually, after starting a new brush stroke, BrushBase::begin is called, which sends the brush settings and a new undo point. Every brush change in the recording is preceded by an UndoPoint, so it doesn't look like the UPs are being selectively swallowed.
BrushBase::end still does get called, since the PenUp command was sent.

If somehow the program is stuck in a state where a penup is registed but it still thinks the stroke is ongoing, it could explain the lack of UndoPoints, but I'm not sure how it could cause the strokes to only show up in the recording. (Some weird interaction with the retcon module is probably the cause here.) However, if the bug is caused by a missing begin() call, the stroke smoother is the most likely place where the bug exists. I'm releasing a new version tomorrow, which includes some changes to the smoother, so if the bug is there, it might fix it.

**Comment by VivaLaVaati** [comment] 2015-08-08 15:02
Ah, alright.

Im not sure what to say to this but it actually does make sense, so i hope
it gets fixed. its weird how its showing up in the recording??

**Comment by Luna-Rex** [comment] 2015-08-10 19:37
I've got a similar issue. Offline mode doesn't have this problem at all for me, but (as either the host or client of a server) creating a new layer, drawing on it and then undoing both of those steps will cause the issue to happen. After that, creating a new layer and attempting to draw on it will cause the new layer to immediately vanish.

At that point, the only way to create a new layer is to create two layers at the same time. (the first one gets deleted when the second is created) Doing it twice in a row will stop me from being able to create a new layer at all.

Rejoining the server fixes it completely.

This bug exists in the latest stable release. (1.0.1.1 on Windows)

**Comment by callaa** [comment] 2015-08-10 19:59
Ok, that sounds consistent with the missing begin() calls. Each layer creation is preceded by an UndoPoint, and normally the beginning of each stroke too. However, if brush's begin() function is not called, that last UndoPoint is not sent. When undoing, it undos everything up to the second layer creation.
Since the bug exists in 1.0.1, it means the smoother is *probably* not the cause.

Some experiments to try:
* After creating a layer, try changing the brush shape or color. If the change does not happen, it means begin() is not being called. If the change does happen, will undo work?
* Does setting the smoother to zero or some nonzero value have any effect?

**Comment by Luna-Rex** [comment] 2015-08-10 20:21
The change in size and color does get shown in the brush previewer after creating a new layer, but undoing the layer afterwards still causes the bug to happen.

The smoother didn't seem to have any effect, regardless of what it was set to.

**Comment by callaa** [comment] 2015-08-11 18:51
Does the brush size or color change take effect when drawing too?
If the brush does change (and not just in the preview, but on the canvas) then begin() is being called. If it does not, then it would seem the begin call is missing.
If the stroke is drawn with the new brush, does undo work then? If it doesn't, then it means the tool change message was sent, but the UndoPoint is somehow ignored.

Also, are you drawing with a mouse or a tablet?

**Comment by Luna-Rex** [comment] 2015-08-11 22:47
The brush size/color changes do take effect when drawing too, even right after creating a new layer. Drawing a stroke with the new brush, undoing it and undoing the new layer still causes the bug to happen, though.

I tried it with both my mouse and tablet, it happens using either one.

**Comment by callaa** [comment] 2015-08-12 14:59
Ok, that rules out the input handling code as the location of the bug.

**Comment by IceCreamYo** [comment] 2016-11-17 14:55
Calla, I'm having the EXACT same problem as Vaati, but I discovered something:
If I go to "edit" and then "recolor selection", everything I drew somehow becomes visible, and then when nI draw over that, it's erased.
Also, the first time I opened Drawpile, I didn't have that problem. I did some things without looking and then I had the problem. I tried going to AppData and deleting the Drawpile folder and then reinstaled Drawpile, but the settings I made just stay, I don't know how to delete them. I kept the Navigator and the Color selection on the left like the screenshot before reinstalling, but after reinstaled It was the same problem and the same setting.
![image](https://cloud.githubusercontent.com/assets/23526310/20393936/8ad938f8-acbc-11e6-9bc7-58cdeed872ab.png)

**Comment by Wade821** [comment] 2019-11-20 06:00
Drawpile has changed a lot (2.1.14) since this issue was last referenced, since 2.0 was released March 18, 2017. To clean up old issues, I'm going to close this issue. If it's still an ongoing problem, please feel free to reopen this issue or join the Drawpile official Discord as noted below.


_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Closed by Wade821** 2019-11-20 06:00 UTC
Labels: Bug
