### ISSUE TITLE
2.1.13 Pressure sensitivity not working after update

### ISSUE THREAD

**Issue by Ibrahnab** [drawpile/Drawpile#826] opened 2019-11-12 19:17 UTC
Hello,

I've been using drawpile for the past year or so with my friends and it has always worked fine on the same tablet that I've been using throughout (Wacom Cintiq 13HD). But immidiately after the recent update, pressure sensitivity completely stopped working. I've looked at all previous related issues from other users and tried their solutions and also what's written on the drawpile homepage, but i got nothing...

Here's a list of what I've tried
*Restarting tablet drivers
*Restarting computer
*Windows Ink Enabled/Disabled
*Updating tablet drivers
*Uninstalling and reinstalling drawpile
*Tried Tablet Tester: pressure doesn't work there either.
*Tried other software like Photoshop/CSP: pressure sensitivity works fine on them

Here's what the log file outputs on startup
![dp_debug](https://user-images.githubusercontent.com/21294842/68701698-a11d5780-0587-11ea-9b23-a98f1586e19b.JPG)

It says loaded Windows 8 pointer but I've always been on Windows 10 when using drawpile...

Also, might be an unrelated to this but after the update, along with the pressure not working, the UI became unusually large. It's really annoying as i can't see the other tools...

![dp_debug2](https://user-images.githubusercontent.com/21294842/68701977-328cc980-0588-11ea-8f85-04d6bac5be53.JPG)

Any ideas on what's wrong here?

Thanks in advance!

**Comment by callaa** [comment] 2019-11-12 20:07
Have you tried disabling windows ink mode in Drawpile's settings? Also, which version did you upgrade from?

The UI being extra large is probably caused by me enabling high-dpi scaling. I'll probably need to revert that in the next release if it's causing more problems than fixing.

**Comment by Ibrahnab** [comment] 2019-11-13 13:13
Yeah i disabled the windows ink mode in Drawpile's settings. I'm not sure which version i upgraded from it must have been somewhere around 2.1.12 or a bit earlier. This issue happened roughly two weeks ago...

**Comment by Wade821** [comment] 2019-11-13 14:51
Couple of questions for you! :) Do you happen to have multiple screens or just one? Which version of Windows 10 are you running? You can find the version by by pressing the Windows logo key and the letter R at the same time, type in "winver" (without quotes) and hit enter. 

Pen pressure settings, in order to work, must ALWAYS match how your tablet is configured. That is to say that if Windows Ink is enabled in your tablet, it should be enabled in Drawpile. Conversely, if it is disabled in your tablet then it should be disabled in Drawpile. The setting may not be always called windows ink in your tablet settings either! You might not have pen pressure yet, but I'd like to make sure that at least this much is set correctly before proceeding further. I realize it works elsewhere given your first post and steps already attempted, but I still want to make sure they match and that we know what it is supposed to be.

![image](https://user-images.githubusercontent.com/18544575/68774166-e96d6180-05e9-11ea-97c6-cb8bbcccae99.png)

![image](https://66.media.tumblr.com/2fcbd12591989d4b9d2b65739357a0bb/tumblr_inline_no0ulcVAQl1sf2eug_500.png)


As far as the big icons, this is probably due to scaling issues set in Windows, as the new version updated with high DPI icons to accommodate such screens. Right click your desktop, go to "Display Settings", and under the section "Scale and layout", check what the % is set to for the scale. After setting this to a lower value, you may need to sign out and sign back into the computer for the settings to fully take affect. Try that and let me know how that works for you.

**Comment by Ibrahnab** [comment] 2019-11-13 17:11
Yeah i forgot to mention, i made sure that the Windows ink matched on both my tablet and on Drawpile. And I'm technically running on two monitors, a regular one and my tablet acts as the second monitor.
![drawpile_debug3](https://user-images.githubusercontent.com/21294842/68784956-ae951900-063d-11ea-8279-c6d3fbc9aeb1.JPG)

However! The solution for the scaling problem you mentioned at the end not only fixed the icons so that they are the appropriate size, it also fixed the pen pressure issue! i switched from 150% to 100% and pen pressure started working somehow.

![debug_100](https://user-images.githubusercontent.com/21294842/68785795-fa948d80-063e-11ea-8ae2-fb6841a85954.JPG)

And just to try it out, i switched back to 150% to see if pen pressure would stop working, and it actually stopped again. 
![debug150](https://user-images.githubusercontent.com/21294842/68785867-16982f00-063f-11ea-9ac6-7e59d002a60e.JPG)

So I'm running on 100% from now on and everything is fine with the UI and the pen pressure. Thanks a lot for the help! I really didn't expect the scaling issue to be related to pen pressure, but I'm not complaining :P 

In case you're still interested, my Windows version is 1903(OS-version  18362.418)

**Comment by Wade821** [comment] 2019-11-14 14:54
That is... unexpected. I did not realize the scaling had any impact on the ability to deliver pen pressure myself. Also sorry for not responding last night, I was busy with work and exhausted. I have to get going now for work but I compiled a list of different things that have resolved tablet related issues in Windows.

**My experiences with pen pressure related problems have been fixed by the following:**
- Making sure tablet settings match Drawpile settings.
- If using an older version of Windows 10 (particularly 1803), there were some issues some users have reported with drawing in this version that were resolved by updating to 1903. 
- If using multiple monitors in mouse mode on a non-display graphics tablet, make sure that the tablet is configured to one monitor under the "pen mode" screen mapping as this seems to impact pen pressure.
- If using multiple monitors in mouse mode on a display graphics using "pen display to other displays", set your main display to be your cintiq device (right click desktop, graphics properties). 
![image](https://cdn.discordapp.com/attachments/546260997703467009/642498814292262932/unknown.png)


Some of this weirdness is probably because of Krita, since Drawpile pulls it's Windows Ink and Tablet support from it. I'd suggest installing it to test if it happens there as well since they're related to some degree, and also because it has a shell plugin that will allow you to see .ORA files as thumbnails in explorer so you can see their contents. 

**Finally, I'll provide a post with the information I made on the Drawpile Discord on 4/28/2019 regarding my own issues with pen pressure:**

So I think I finally understand my multi screen pen pressure problem with Wintab a bit better. If I have my Tablet Mapping under pen mode set to ALL screens as displayed here (even though I use mouse mode), I only seem to receive pen pressure near the outer edge of my screen configuration. This depends if I'm using the bottom left, bottom right, or top middle screen.

![image](https://cdn.discordapp.com/attachments/544996573600284675/572263240047001600/unknown.png)

If I set it this way in pen mode, when using mouse mode on my tablet...
https://cdn.discordapp.com/attachments/544996573600284675/572263395731177483/unknown.png)

I only receive pen pressure while using the bottom left monitor. If I move the Drawpile window to the bottom right monitor or top middle, I no longer get pen pressure at all. Even though it's working in mouse mode. So it seems that the settings in pen mode for Wacom at least, can influence where Drawpile can receive pen pressure information in a multi monitor screen setup. So what I'm saying is that even though I use my tablet in Drawpile LIKE this all the time...

![image](https://cdn.discordapp.com/attachments/544996573600284675/572264746204528640/unknown.png)

The setting for what screen area is set to be used in Pen mode highly influences how pen pressure works in Mouse mode for Drawpile. For some reason. As you can see I have four display screens, but only three are active (1, 4, and 2) which is the case most of the time.

![image](https://cdn.discordapp.com/attachments/544996573600284675/572265053810851850/unknown.png)

This is all in one online session, without exiting or restarting Drawpile. Don't know if you can do anything but I figured I'd tell you what I discovered, since I now seem to understand better why I get pen pressure, and why I don't. I also made a video that's 2 minutes long. Sorry if it gets a bit dizzying, I can't record all three monitors at the same time.

https://youtu.be/8OJWMoAAHZw

**Comment by Wade821** [comment] 2019-11-28 20:48
Since I received no response, I’m going to close this issue. If this is still a problem, please comment so we can reopen this issue.

**Closed by Wade821** 2019-11-28 20:48 UTC
Labels: Support
