### ISSUE TITLE
Touchbar can't be used to zoom in/out

### ISSUE THREAD

**Issue by fariparedes** [drawpile/Drawpile#946] opened 2021-01-02 23:57 UTC
I have a Kamvas Pro 13, and I'd like to be able to use the touchbar to zoom in and out like I do in CSP and Photoshop. However, this functionality doesn't seem to be supported by drawpile.

**Comment by Wade821** [comment] 2021-01-03 01:51
I don't think I'd call it an issue worthy of being opened here on github, since it's not a bug nor does it need to be a feature request. This is merely a matter of how the manufacturer is working with those programs (in terms of what information and/or shortcut info it's sending to the programs). Likely because those programs are larger and more well known. 

You should be able to work around that issue by defining a shortcut key from what I read. You can also apparently set application specific settings. You can find [zoom settings for Drawpile on the website.](https://drawpile.net/help/shortcuts/), but I'll note them below:

**Zooming: There are three zooming methods:**
- Zoom in/out with Ctrl++ and Ctrl+- (customizable)
- Zoom with Ctrl+mouse wheel up&down
- Hold Ctrl and drag up & down.

You can also customize settings in Drawpile by going to edit, preferences, and look at "Canvas Shortcuts" or "Shortcuts" to view and change any settings there. 

Closing this issue but you can feel free to respond, or join the Drawpile Discord server. Invite link is on the website in the lower left corner. 

![image](https://user-images.githubusercontent.com/18544575/103470111-09e70680-4d2b-11eb-9024-c2b572ffd95b.png)

![image](https://user-images.githubusercontent.com/18544575/103470107-03588f00-4d2b-11eb-86dd-0f7f23e2ca92.png)

[Source - Huion Kamvas Pro 16 Review](https://digitalarttabletguides.wordpress.com/2019/06/12/huion-kamvas-pro-16-review/)

**Closed by Wade821** 2021-01-03 01:51 UTC
Labels: Invalid, Support

**Comment by fariparedes** [comment] 2021-01-07 23:59
Hi @Wade821,

Further testing has revealed that the touchbar (which is the thing in your screenshot there between the buttons) is capable of zooming out the canvas, but not zooming in. Since I have software from 2007 which supports this functionality, and it also works on my web browser, I sincerely doubt it is anything other than a scrollbar which automatically sends the Ctrl+ input for standard zoom in/out functionality. Thus, I would have to determine that this is not a manufacturer issue.

**Comment by Wade821** [comment] 2021-01-08 03:48
That's good to know, but ultimately doesn't change my previous answer. What you're asking is actually pretty unreasonable for the reasons I will list below. 

The Kamvas Pro 13 has application specific programmable settings, so you can configure the buttons to work specifically for any application you desire. The settings for which it "automatically" works on browsers, Krita, and Photoshop are more than likely because those applications are well known. Therefore, it's likely that the manufacturer designed the tablet to switch what keys are used to scroll/move/zoom for those well known applications. By providing alternate programmable settings, they have essentially already addressed the concern of having it work with other programs. If you want it to "just work" out of the box, that makes it a manufacturer issue by default. 

Additionally, it's not so simple as "make this work". One also has to consider that to make it work, someone would have to use capture software to figure out what Kamvas is sending to Drawpile to try and zoom or zoom out. Then that information would have to be determined as to what forced changes would this set on Drawpile and affect other shortcuts. A test build would have to be made and tested not only by you, but other users to make sure it doesn't break existing functionality. That is a whole lot of unnecessary work, when your tablet supports manual configuration of tablet touch bar settings. 

If Drawpile changes the way it works, that would in turn cascade other changes to default shortcuts that would probably have to be changed. Other tablet users then in turn would demand it be set back. For example, my Wacom Intuos5 Touch Medium Pen Tablet (PTH-650) already works with the default settings from Wacom when I set mine to zoom, using the setting change button and the touch dial to zoom in clockwise or zoom out counter-clockwise. 

![image](https://user-images.githubusercontent.com/18544575/103971653-692c8880-5128-11eb-9bb4-617c580d0f59.png)

Have you even tried setting customized options? You never even mentioned that. I'm going to append to some of the instructions below though, because there are some small caveats you should know about which I apparently forgot to mention.

**Zooming: There are three zooming methods:**
- Zoom in/out with Ctrl**+**+ and Ctrl**+**- (customizable, Ctrl **+** the + symbol should either use the separate 10 key number pad + symbol or if it's the numbers above the letters, use Ctrl **+** Shift **+** + symbol)
- Zoom with Ctrl+mouse wheel up&down
- Hold Ctrl and middle click, then drag up to zoom in & down to zoom out.

**Comment by Wade821** [comment] 2021-01-08 04:07
I took a moment to consider those caveats and how they might compare to those other programs you mentioned since I have them installed. My findings are as follows:

- Photoshop and CSP works with Ctrl *plus* + regardless of it being the number pad + or the number row +. Both programs refuse to zoom in when attempting to use Ctrl *plus* Shift *plus* the + on the number row.
- Drawpile and Krita works with Ctrl *plus* + with Number pad, and Ctrl *plus* Shift *plus* the + on the number row.
- All programs work properly with zoom function on my Wacom tablet using the touch dial. 

As such, I'm still not convinced this is a program bug/issue. I still think you'd be better suited to using the customizable settings on your tablet.
