### ISSUE TITLE
Feature request: rotation on transform tool

### ISSUE THREAD

**Issue by ParisGreen** [drawpile/Drawpile#494] opened 2017-07-18 15:19 UTC
Truth be told, I don't really know if this is feasible or not, but it would be really convenient to be able to rotate a selection while transforming it.

**Comment by Le2222** [comment] 2017-07-20 16:03
this seems to be the same issue of the topic #483 
So, i guess the problem is: the rotation feature is hidden/hard to find

I agree with this, honestly i thought about create a topic requesting the rotation tool aswell because I couldnt find it.

**Comment by callaa** [comment] 2017-07-23 08:18
This is indeed a usability issue since many people have difficulty finding the feature. One way of making it more discoverable might be to change the resize handles into rotation handles when alt is pressed down and (as Le2222 pointed out) make the handles actually usable for rotation.

**Comment by blurymind** [comment] 2017-07-23 14:09
Perhaps add extra handle for rotation?

**Comment by VRArt1** [comment] 2019-09-05 10:49
Yeah it would be best to make it more obvious that it's a feature. I just came in to mention how useful a rotation feature would be for this program only to find out it apparently has existed in the shadows for two years now.

**Comment by Wade821** [comment] 2019-09-05 18:56
It's already been made and will be available in the next version,  as documented in the tumblr dev diary. 

https://drawpile-dev-diary.tumblr.com/post/186908649027/better-selection-tool

**Comment by Wade821** [comment] 2019-11-20 07:03
Released in Drawpile 2.1.12. Closing issue.
https://drawpile.net/news/release-2.1.12/

**Closed by Wade821** 2019-11-20 07:03 UTC
Labels: Usability
