### ISSUE TITLE
Pen Pressure Sensitivity lost in V2.1.5

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#722] opened 2019-03-30 20:16 UTC
Hi,

I know Drawpile has some issues losing the pressure sensitivity in some occasions, is a problem that I have faced some times. After installing V2..1.5 the usual workarounds didn't worked, so I decided to share the issue here.

These are my Drawpile preferences:

![image](https://user-images.githubusercontent.com/3485891/55281160-ff960e00-52f5-11e9-8f46-61cfb61e20d0.png)

![image](https://user-images.githubusercontent.com/3485891/55281093-053f2400-52f5-11e9-8317-0cfc7b126680.png)

My SO is Windows 8.1 64 Bits, using the same Wacom driver than before update Drawpile and I double check if my tablet was being detected (it works fine in Krita and Photoshop too, even the older version of Drawpile that I have installed in a different directory, EDIT: I even installed again the previous V2.1.4 version over this new one, without restarting and it worked fine, without un-install the new version first):

![image](https://user-images.githubusercontent.com/3485891/55281110-47686580-52f5-11e9-92cd-ee768b961593.png)

When I faced this kind of issues in Drawpile, I created a little .bat file with the next commands in order to restart Wacom services in windows, and after that I just closed and open again Drawpile (it worked always indded):
![image](https://user-images.githubusercontent.com/3485891/55281139-c2ca1700-52f5-11e9-8343-9ee5b7995746.png)

All these things were checked again after restarting the PC (just in case, because "Windows things")

Regards

**Comment by callaa** [comment] 2019-03-30 20:25
This is likely related to me updating the bundled Qt version to 5.12. I think the problem is related to Wintab mode. Can you check the log file (Help menu) to see whether it's using "Win 8 Pointer Input" or "custom Wintab support"? (This message is printed right when Drawpile starts)

**Comment by erik90mx** [comment] 2019-03-30 20:48
I tested with V2.1.4 and V2.1.5 installing one at the time, to get the Log files in the same scenarios.
[drawpile-2.1.5-2019-03-30.log](https://github.com/drawpile/Drawpile/files/3025929/drawpile-2.1.5-2019-03-30.log)
[drawpile-2.1.4-2019-03-30.log](https://github.com/drawpile/Drawpile/files/3025930/drawpile-2.1.4-2019-03-30.log)

I doudn't found what you mentioned in V2.1.5 but in V2.1.4 it was using Wintab
![image](https://user-images.githubusercontent.com/3485891/55281487-bbf1d300-52fa-11e9-8f5a-24148fc5f4b4.png)

Regards

**Comment by callaa** [comment] 2019-03-30 21:08
Okay, as I suspected. Both 2.1.4 and 2.1.5 should print the same message.

**Comment by Bunnily** [comment] 2019-03-31 00:59
I'm having a similar problem but I'm not getting pen pressure at all no matter how I try unless I activate windows ink which brings another slew of problems, like an onscreen keyboard (Which I don't need) and annoying ripples and circles when I hold down my tablet stylus. I'm using the XP Pen Artist 12 and I updated to the latest driver so it isn't that. It also doesn't have anything to do with restarting the driver as I've tried multiple other programs like CSP and SAI and the pressure works fine on both of them.

**Comment by callaa** [comment] 2019-03-31 06:48
I'm pretty sure this problem is caused by me updating to Qt 5.12. Now to see if it can be fixed without reverting back to 5.11...

**Comment by callaa** [comment] 2019-03-31 07:33
Mystery solved! Somehow, the build setting that enables the improved tablet code was missing from the new build! I don't know how...

**Comment by callaa** [comment] 2019-03-31 08:15
Here's a new build of 2.1.5 with KIS_TABLET enabled and the latest wintab code copied over from Krita: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test.zip

Does this fix the problem?

**Comment by erik90mx** [comment] 2019-03-31 08:37
> Here's a new build of 2.1.5 with KIS_TABLET enabled and the latest wintab code copied over from Krita: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test.zip
> 
> Does this fix the problem?

It does nice and smooth 

![image](https://user-images.githubusercontent.com/3485891/55286810-ea54ca00-535d-11e9-8c2a-2161c3ea7ea4.png)

**Comment by erik90mx** [comment] 2019-03-31 08:54
It has a weird brush visualization movement glitch as you can see here (I'm not moving the pen like that, it is a continuos movement and fluent), but it doesn't affect the actual brush movement when you are doing the strokes.

![brush_moving](https://user-images.githubusercontent.com/3485891/55286954-dad68080-535f-11e9-8c7d-13ba5d4aecaf.gif)

Regards

**Comment by callaa** [comment] 2019-03-31 09:14
That's regular tablet jitter, I think. If you set the smoother down to zero, the brush movement will be jittery too.

**Comment by erik90mx** [comment] 2019-03-31 09:48
Well this time I recorded with another program, and the movement seems more similar at what I'm seeing trough the monitor, I changed my cursos to a cross in order to make more notable the jitter:
![brush_moving2](https://user-images.githubusercontent.com/3485891/55287541-7ddec880-5367-11e9-9111-0e95d385aa8b.gif)

This is my actual input configuration, even with smooth at 0 the jitter shows up a lot.
![image](https://user-images.githubusercontent.com/3485891/55287560-c4ccbe00-5367-11e9-822c-81868dfa247f.png)

Regards

**Comment by pachuco** [comment] 2019-03-31 11:22
Albeit I am using windows XP and manual compatibility enforcement, confirming loss of pressure in 2.1.5, with it working in prior version.

Tablet is XP-PEN G430S.

**Comment by doornob** [comment] 2019-03-31 18:12
> Here's a new build of 2.1.5 with KIS_TABLET enabled and the latest wintab code copied over from Krita: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test.zip
> 
> Does this fix the problem?

I had lost pressure in the newest update as well and I gave this a quick try. It gives pressure back but it also causes a cursor offset by about half a centimeter making drawing very difficult.

**Comment by Banderi** [comment] 2019-03-31 22:26
Can confirm the crosshair jumps around like crazy - the easiest way to reproduce and see for yourself is to pan the view with the tablet pen, and the whole canvas will jitter around.

**Comment by callaa** [comment] 2019-04-01 14:55
Another test build: https://drawpile.net/files/win/drawpile-2.1.5.tabletfix-test2.zip

This one should have the exact same behavior as 2.1.4

**Comment by erik90mx** [comment] 2019-04-01 21:28
Thanks a lot, It works very good now:

![brush_moving4](https://user-images.githubusercontent.com/3485891/55360800-aa433380-5492-11e9-82ef-5cc1498bad0f.gif)

Regards

**Comment by doornob** [comment] 2019-04-02 01:31
It works!
Thank you Callaa for all the work you're doing for us.

**Closed** 2019-04-06 09:54 UTC
Labels: Tablet
