### ISSUE TITLE
Host dialog: add private/public toggle

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1280] opened 2024-04-11 08:53 UTC
Add an easy private/public toggle to host dialog, defaulting to the former. Probably already considered in the redesign issue.

**Comment by askmeaboutlo0m** [comment] 2024-04-11 11:49
Duplicate of #1220. There's more things wrong with the host dialog, it doesn't make sense to do this task in isolation, the work would just get thrown away.

**Closed by askmeaboutlo0m** 2024-04-11 11:49 UTC
Labels: duplicate
