### ISSUE TITLE
Drawpile's flatpak package has the unnamable gtk3 save file dialog bug

### ISSUE THREAD

**Issue by Inky1003** [drawpile/Drawpile#1035] opened 2022-07-08 23:25 UTC
When I save a drawing in Drawpile's flatpak version, It does not allow me to name the file. Instead, It searches inside the current dialog directory.

https://gitlab.gnome.org/GNOME/gtk/-/issues/326
Related to the bug above. Seems not to be a bug with flatpak packages, as them seem to work fine with the same dialog.

- The problem is only in Drawpile's flatpak, AUR Drawpile version is fine.
- The problem is only in Drawpile. Other flatpaks seem to be working well.
- As It should be noticed, I'm using Arch Linux, but when I was using Manjaro a few days ago, all of my flatpaks were updated and the problem were not there.

**Comment by askmeaboutlo0m** [comment] 2023-03-24 12:18
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Duplicate of #833.

**Closed by askmeaboutlo0m** 2023-03-24 12:18 UTC
