### ISSUE TITLE
Appimage not maintained

### ISSUE THREAD

**Issue by Ricky-Tigg** [drawpile/Drawpile#853] opened 2020-01-06 12:35 UTC
Searching at [Github](https://appimage.github.io/apps/)  an upstream-generated AppImages software available without mention  _no valid OpenPGP data found_, i decided to focus on your application.

![Appimage org_Drawpile_1](https://user-images.githubusercontent.com/26058215/71817805-c1e9c100-308f-11ea-8d7d-4583859563e2.png)
![Appimage org_Drawpile_2](https://user-images.githubusercontent.com/26058215/71817817-cdd58300-308f-11ea-8512-54a1da89b3fa.png)

Once link is clicked i notice file is not [there](https://appimage.github.io/Drawpile/) –probably as intended– to be available for download.

At that [page](https://drawpile.net/download/#Linux). Application is available for download as universal formats _Appimage_ and _Flatpak_ respectively as 2.0.11 and 2.1.14.

Is Appimage format aimed to be no longer maintained?

**Comment by notfood** [comment] 2020-01-06 22:46
Duplicate of https://github.com/drawpile/Drawpile/issues/697

Help is wanted for a proper AppImage as there is difficulties to get it running properly.

**Closed by notfood** 2020-01-06 22:46 UTC
