### ISSUE TITLE
Tablet Pen Button

### ISSUE THREAD

**Issue by coffeemugtime** [drawpile/Drawpile#289] opened 2016-01-22 23:52 UTC
Hello. I use a Cintiq 22HD on Windows. On my tablet pen buttons I bounded them to zoom in (bottom button {Ctrl}{=}) and zoom out (top button {Ctrl}{-}). Whenever I zoom in on a drawing it leaves marks on it. Zooming out works normally. Turning on the opacity of the brush seems to nullify the effect.

**Comment by callaa** [comment] 2016-01-23 12:08
Sounds like application is receiving a tablet press event in addition to the custom keys. If enabling sensitivity hides it, the initial press event probably has a pressure of zero. I'll have to try and see if I can reproduce this to see if there is some way of distinguishing the unintended dab from intentional ones.

**Comment by callaa** [comment] 2018-02-14 15:34
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Closed by callaa** 2018-02-14 15:34 UTC
Labels: Tablet
