### ISSUE TITLE
Distorted lineart during Brush Strokes

### ISSUE THREAD

**Issue by Miumix** [drawpile/Drawpile#346] opened 2016-07-25 01:01 UTC
I just started to try out the newest update and I realized that my brush stroke shakes a lot, making my lineart look pretty distorted . . .

![samp1](https://cloud.githubusercontent.com/assets/13894094/17087754/4615d060-51df-11e6-9cd7-c046d9cf22ab.PNG)

The funny thing is that It only causes conflict with a part of the canvas (left one). I tried different settings but without success. Is someone else getting this issue?

**PS.** Regarding [Issue #249] the bug still exists, my friends and me barely can draw with such a lag.

**Comment by callaa** [comment] 2016-07-25 14:21
Since it affects only part of the screen, it is probably caused by the driver. Now that Krita has been ported to Qt5, I'll take a look if I can copy their tablet driver interface code, since it seems to work much better than Qt's built-in stuff.

**Comment by Miumix** [comment] 2016-07-25 16:21
Ok, Let me know how this was.
Thanks, Calla O v O/

**Comment by Miumix** [comment] 2017-04-02 18:34
Just to let you know that thanks to the newest updates the lag issue is fixed now. However, I'm still unable to draw on the left part of the screen because of distorted strokes:

![new canvas](https://cloud.githubusercontent.com/assets/13894094/24589680/8f8e8424-17ac-11e7-8e36-b8ff3462b375.jpg)

Previously, you mentioned that this is probably caused by the tablet driver. Is that a compatibility issue? I don't know if this will help but I use Genius G-Pen 4500 to draw the most of times. Also I have another tablet I barely use: Genius EasyPen M506. I've not installed the last one yet after a recent hard disk formatting, so that shouldn't be the source of the current issue.

Again, thanks for all the hard work you've done so far ♥

**Comment by Miumix** [comment] 2018-01-28 20:02
Fixed by enabling "Bug workarounds" option. I'm getting dots on the end of the brush stroke because that though, but at least I'm able to draw in drawpile again~

**Comment by callaa** [comment] 2018-02-14 15:33
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Closed by callaa** 2018-02-14 15:33 UTC
Labels: Tablet
