### ISSUE TITLE
Cursor lag with tablet laptop

### ISSUE THREAD

**Issue by Zoeykoko** [drawpile/Drawpile#301] opened 2016-03-04 07:30 UTC
This is a bit of an odd problem that I've never encountered before with drawing programs.

I'm using a Lenovo Yoga tablet laptop and Windows 8.1. It's maybe two years old tops, and can run 4 Adobe programs at once without any lag so I don't think it's a problem with my laptop being slow. 

I suppose the best description is that the cursor lags each time I touch the pen to my screen, resulting in a split second where each new line is jagged, but only at the very start. Er, mostly. Sometimes it comes back on super long strokes even on the best settings I can manage.

https://gyazo.com/2e8a562147bb112c2252961455776372

I've fiddled with the input panel in every way I can think of, and nothing keeps this from happening. This is just enough to render Drawpile unusable for me, which is disheartening because it's so perfect in every other way.

Everything else seems to be working, like pen pressure. It almost looks like Drawpile is trying to read my tablet pen as a left click at first, which causes the split second lag. (If you tap and hold the tablet pen, it makes a little circle around the tip appear and when you let up, it registers it as a left click. That little circle appears for a split second each time my pen taps the screen, but only in Drawpile.)

Has anyone else had this problem? I've perused the existing issues and haven't found anything that directly relates to this, as it's not an issue that can be resolved with the smoothing curve.

**Comment by range4life** [comment] 2016-07-12 08:06
it's seemingly not a "lag" of sorts. it seems like the input is only registered after your cursor has moved a certain amount of space. i have this issue too, and it is terrible.

**Comment by callaa** [comment] 2016-07-28 17:38
Someone at the facebook group had a similar problem recently. In that case, the problem was caused by Windows's pen gestures. (Other programs can signal that pen gestures should be disabled for the canvas, but I'm not sure how that is done.) Try disabling stylus gestures from Windows's control panel and see if it has any effect.

**Comment by range4life** [comment] 2016-07-30 09:04
It is from windows' pen gestures. The problem i had was solved by turning off the **STARTUP** service Tabletpcinputpanel / Tabletinputservice / Touch keyboard and handwriting panel service (all seem to be the same thing) as many others online will say. This was on windows 10.

The difference in this case was that it required me to restart to refresh the registry after the service was closed manually but it kept relaunching on startup. Turning off flicks or hold to right click did not do anything. Super frustrating. Hoping anybody who gets here from google is helped.

But yeah, this does not seem to be issue with your software in particular. Although, I do not believe paint tool SAI had the same issues with the service, though I can't be certain, and definitely can't be assed to recreate it :p.

**Comment by callaa** [comment] 2018-02-14 15:34
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.

**Closed by callaa** 2018-02-14 15:34 UTC
Labels: Tablet
