### ISSUE TITLE
Keybind Presets

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1346] opened 2024-07-18 11:21 UTC
Given that Drawpile is a cooperative application, it would make sense for there to be presets that allow users to select the keybindings they're already familiar with.

This involves importing the default keybinds of popular applications, and importing their customized keybindings. 

This functionality may be implemented in the start screen (#1345).

**Comment by askmeaboutlo0m** [comment] 2024-07-18 11:25
Dupe of #1206.

**Closed by askmeaboutlo0m** 2024-07-18 11:25 UTC
Labels: feature
