### ISSUE TITLE
Bug: Smudging Tool

### ISSUE THREAD

**Issue by dustiibunnii** [drawpile/Drawpile#944] opened 2020-12-21 21:27 UTC
Hello!  I have a few features to request, or suggest!

- The brush system here is a bit difficult to grasp, however after a bit most get it. Though, I was wondering if we  could rename presets or something like that, or even, have the paint system work like firealpaca or paint tool sai, photoshop--  more like, having a list of brushes and their names, which changes their presets, and even having some kind of way to create our own textured brushes and add them, group via folders... You know how firealpaca can upload bitmap files and alter settings in a brush zone? Or even upload code files for those patterned brushes.

- Folder support for layers. I am not sure how feasible my thoughts are, but I thought I could put it out. Perhaps there could be a way to drag and drop layers into folders, collapse them, and on top of being able to control each individual opacity, control the grouped opacity.

I do realize that drawpile is orientated for the mass user, and the drawing on one canvas thing, however I thought these would  allow users to get more comfortable with being able to use brushes that are more suited to be added/removed, named, customized, etc... As well as, the  blur/smudging tool seems to  be buggy? For me, it creates this weird rainbow-edged glow smudge when it's a really large brush size.

Also, I did read about  someone  doing  something on  Rust, and revamping the core Drawpile thingos- that's pretty awesome.
Thank you for considering this if you do!

**Comment by Wade821** [comment] 2020-12-23 04:48
Pretty sure all of this has already been requested. I would close this for being a duplicate of those open issues, but that blur issue you mentioned will need more info here before I do that. If you have specific suggestions, try checking open issues to first make sure there isn't something out there already (so we can avoid mass open issues), and then comment on those as far as ideas and feedback. 

Also, if you think you have a bug, I'd avoid posting it in the same post as feature requests. In general, if you have problems, I suggest joining the Drawpile Discord server, for which the invite link can be found on the website in the lower left corner.

- Feature request: Brush Preset naming and preset stroke preview --> #800
- Folder support for layers ---> #261 

As far as your blur tool (#662), it's not really blur but smudge tool. It's more of like, how much the color blends in with nearby color as you paint with a color. Post some screenshots here regarding that to explain more of what you mean.... or maybe a small video of some sort.

**Closed** 2023-03-23 12:54 UTC
Labels: Bug, Support
