### ISSUE TITLE
image/video export error

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#319] opened 2016-04-07 09:08 UTC
returns 'corrupted double-linked list'
.dprec file about 40mb
drawpile built from source linux mint 17.3

video export
http://s6.postimg.org/o2jehx6wx/vid_Export.jpg

image strip export  
http://s6.postimg.org/hnkdl9075/img_Export.jpg

**Comment by Wade821** [comment] 2019-11-28 22:25
Given the age of this and the fact that I can't reproduce it, I'm going to close it. Please comment if this is still an ongoing issue so it can be reopened. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Closed by Wade821** 2019-11-28 22:25 UTC
Labels: Bug
