### ISSUE TITLE
QA: More info about the Docker setup

### ISSUE THREAD

**Issue by gerroon** [drawpile/Drawpile#810] opened 2019-10-23 19:14 UTC
Hi

I set up the server using DOcker based on the help page, all seems well explained but I cant find a way to connect to the server using the client app. I guess I am not able to find a way to create a joinable room on the server side? Is it possible to explain that further?

thanks

**Comment by callaa** [comment] 2019-10-23 19:19
If you can't connect to the server, the problem is likely in one of these two places:

1. The server firewall. Whether there is a default firewall depends on the distro. If you run `iptables --list` and it prints out lots of rules, then you have a firewall and need to allow traffic to port 27750. (Generally, it's a good idea to have a firewall and block all the ports you're not using.)
2. Exposing the port from the container: when running the container, this argument must be included: `-p 27750:27750`

**Comment by gerroon** [comment] 2019-10-23 19:49
Hi

I can connect to the server but I see no rooms, and the server page did not show me how to serve rooms by default with Docker.

Btw this is all local network. And I am using the exact lines for the Docker from the help.

thanks

**Comment by callaa** [comment] 2019-10-24 15:50
Just to clarify. If you host a session on your server, you can't see it when joining that server?
Or are you referring to template sessions? (Preloaded sessions that are always present at a server)

**Comment by gerroon** [comment] 2019-10-24 17:10
Hi

The server is running, and I use the linux client to connect to it. It asks for a user then I do not see any rooms or anything to join, since there does not seem to be a server management ui, I cant generate a new room there.

**Comment by callaa** [comment] 2019-10-24 17:47
You can create a room the same way as on any other server, by hosting it via the "Session -> Host" menu item in the main application.
If you enable the server's admin port (the instructions are on the help page,) you will be able to use the graphical server frontend to remote administrate the headless server. (A web admin site is on the TODO list.)

**Comment by gerroon** [comment] 2019-10-24 18:02
I see, so there is no command line etc to create room on the server, I have to still use the client app to connect to the server to host?

Also to make sure, there is a admin page (I already enabled the admin port), but I cant access control it becasue there is no gui yet?

**Comment by callaa** [comment] 2019-10-24 18:16
Yes, you need to use the client app to create a room. However, there is an alternative way: you can create a session template (easiest way is to use the File -> Export -> Template item in the client.) When a template directory is assigned to the server, it will automatically create rooms from the template files. When such a room ends, the template is reloaded and the room recreated.

There is a GUI. If you're using the windows version, launch drawpile-srv.exe (I don't recall if a shortcut is created for this, but it's in the same directory as drawpile.exe.) Right click on the tray icon and select "Remote", then enter the URL of your remote admin port (E.g. http://localhost:27780/)

**Comment by gerroon** [comment] 2019-10-24 19:03
Hi

Thanks for the explanation. I will try the template stuff.

I am on Linux, and using the Docker install. I guess I wil just wait for the web version.

**Comment by Wade821** [comment] 2019-10-24 20:09
You can do it in linux too, just run the following in the terminal. Note that you use a web host name if the server is not on your network. If it is on the same network as your client computer, use the server's IP address instead. 

```drawpile-srv --gui --remote http://YOURHOSTNAME.COM:27780/```

**Comment by gerroon** [comment] 2019-10-24 20:41
Awesome I will try that.

**Comment by CodyEakins** [comment] 2019-10-29 05:29
@gerroon 
My simple Docker deployment guide covers this topic a bit. 
Mainly about joining a server running on your localhost and hosting sessions to it.

**Comment by CodyEakins** [comment] 2019-11-01 06:15
@gerroon 
Another hopefully useful resource:
https://github.com/brushdojo/drawpile-srv

I just released an open-source version of my community's `drawpile-srv` configuration. 
It's built using Docker, Docker Compose, SQLite, and etc.

**Comment by gerroon** [comment] 2019-11-01 15:49
@ CodyEakins thanks I will look at it.

**Comment by notfood** [comment] 2019-12-25 21:08
Support request has been resolved.

**Closed by notfood** 2019-12-25 21:08 UTC
