### ISSUE TITLE
Host Keys for List Server (support for cluster-type hosts)

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1283] opened 2024-04-11 09:06 UTC
Host Keys for List Server (support for cluster-type hosts).
Please describe and expand upon the feature further in this issue.

**Comment by askmeaboutlo0m** [comment] 2024-04-11 11:50
Duplicate of drawpile/listserver#6.

**Closed by askmeaboutlo0m** 2024-04-11 11:50 UTC
Labels: duplicate
