### ISSUE TITLE
Messy filenames of archived session parts after autoreset threshold reached

### ISSUE THREAD

**Issue by f2d** [drawpile/Drawpile#795] opened 2019-08-04 09:05 UTC
For example, contents of `77333529-9a37-4b08-a1a4-2004749fad88.session.archived` file:
```
FILE 77333529-9a37-4b08-a1a4-2004749fad88.dprec
ALIAS drawparipark
FOUNDER ...
AUTORESET 15728640
...
FILE 77333529-9a37-4b08-a1a4-2004749fad88 (1).dprec
...
FILE 77333529-9a37-4b08-a1a4-2004749fad88.dprec
FILE 77333529-9a37-4b08-a1a4-2004749fad88 (1).dprec
```

Drawpile server currently seems to just look for a first unused name on disk, which after renaming previous files to `*.archived`, results in a mess like this:

![2019-08-04_11-24-26_002309_2019-08-03_06-20-28_77333529-9a37-4b08-a1a4-2004749fad88_crop](https://user-images.githubusercontent.com/4068475/62421694-682f3600-b6ae-11e9-90ad-3a327cdaff24.png)

My problem is, I maintain a script that manages a webpage with archive of recordings, and so I need it to get all parts of recording (instead of just taking the one largest by filesize, as of now). I'll decide something either way (using mod.dates, etc), but have a **suggestion**:

First, look into the session file (example above) and add +1 to the last suffix found there.
Then, look on disk (just in case) to find first unused filename starting at number from first step.
Optionally, start adding numbers from (2), not (1), so it's obvious what it means - second part and so on.

For example, it may become:
```
FILE 77333529-9a37-4b08-a1a4-2004749fad88.dprec
FILE 77333529-9a37-4b08-a1a4-2004749fad88 (2).dprec
FILE 77333529-9a37-4b08-a1a4-2004749fad88 (3).dprec
```
And so on. This way I could just get a list of `*.dprec` files from there, trying to append `*.archived` if not found as is.

**Comment by Wade821** [comment] 2019-08-04 09:27
Can you elaborate on what your script is for your webpage? Potentially, we can come up with something that works for you.  I don't code anything for Drawpile really so I can't comment on the naming scheme here, but I do a fair bit of Linux scripting in bash. 

**Example:**
I've made a bash script for using drawpile-cmd to convert session recordings to JPG, by checking for files to see if a corresponding JPG exists and creating one if it does not. There's also an alternative script which checks for the last file in the series. It will then rename the JPG file created as output with the "year-month-day militaryhour.minute.second - session name".

**Comment by f2d** [comment] 2019-08-04 10:05
The (pile of) scripts are [available here](https://github.com/f2d/drawpile_webpage_automation) with a link to live example, although not advised to use yet, unless someone is OK to get his hands dirty.

Works like this:
1) Drawpile server pipes its log output to awk, which forks a python script into background to update stuff whenever a trigger line of log is met, like user joining or session closing.
2) The python script creates session screenshots, counts users and strokes in recording, and then puts it into a public folder for download. Currently it only processes the largest `*.dprec` file for each session ID.

I could use those files like `{Date Time} session {session ID}.dprec`, which are named in a more consistet order, but:
1) They are usually several hundred bytes smaller (I already checked their difference in `*.dptxt` format, but forgot what it was).
2) Some of old sessions stored on my server, for whatever reason, have only one or another type of recording, from `--record` or `--sessions` commandline argument of drawpile-srv (I dump both into one folder currently).
3) `--record` ones stop after server restart, but `--sessions` ones continue, which is the main reason to use the latter, but they have this naming issue.

**Comment by f2d** [comment] 2019-08-04 11:14
By the way:
1. The server already does renaming the old file to `*.archived` before creating new one.
2. The companion file with session metadata already can contain repeating filenames.

So a simplier suggestion would be to append date-time to old file when renaming it, for example as `{session ID}.dprec autoreset at {Date Time}.dprec.archived`, and recreate the new file as simple `{session ID}.dprec`.

Whatever way it is to become, I'll adapt my script to that, and then manually comb through old recordings to rename and reprocess them.

**Comment by Wade821** [comment] 2019-08-04 20:43
Super cool looking script and output. I'll definitely have to tinker with this myself as time permits, I'd love to have something similar for my Drawpile server script for Raspbian/other Linux distros. But looking at it in depth is just not something I have time to do at the moment, unfortunately.

Anyway, that being said, I'm having a hard time figuring out where I should be looking at your script. To me, it seems you want all the relevant files from a particular session to be more easily gathered, so you don't have to simply get it by the largest file size in order to reproduce the information as session archives with thumbnails on your website. It also appears to me that the main portion of the session archives is the "update.py" portion, for which I have no real practical understanding of python at the moment. 

I had thought earlier if your process was more bash based that I could help with making a script that might work better for your website. Or maybe this is just above my head, and if so I apologize for taking your time. Since I can't seem to offer much in the way of immediate help, I'll post the scripts I was talking about earlier below. I just don't have the time to really dig through your github repository as much as I'd like to do right now. 😢 

### **For the first part, both scripts (convert all DPRECs to jpg and convert last DPREC to jpg) are the same.**
```
#!/bin/bash
bold=$(tput bold)
underline=$(tput smul)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
normal=$(tput sgr0)


dpinstallloc=/home/pi/Public
SessionsFolder="$dpinstallloc/Programs/Drawpile-Srv-Files/sessions-bkup"

cd $SessionsFolder

echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
echo ${bold}${underline}Beginning Search through DPREC Recordings for Corresponding JPEG Files.${normal}
echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
echo
```

### **This is the rest of the script for converting all DPREC files.**
```
DprecArchiveFiles=$(find . -type f -name "*.dprec.archived" | sed 's/.\///g')
echo "$DprecArchiveFiles" | while IFS= read -r line ; 
do

    JPEGname=$( echo $line | sudo sed 's/.dprec.archived/-1.jpeg/g' ) ;
    SessionArchiveFile=$( echo "$line" | cut -c 1-36 ) ; 
    FileModDate=$(date -r "$line" "+%Y-%m-%d %H.%M.%S") ; 
    FileTitle=$(grep -m 1 "TITLE " "$SessionsFolder/$SessionArchiveFile".session.archived | cut -c 7-100) ; 
    NewName=$( echo $FileModDate - $FileTitle )
    echo
    echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
    echo
    if [[ -e $SessionsFolder/$NewName ]]; then
        echo "${green}JPEG Located${normal}: $NewName".jpeg
        echo "This file corresponds to DPREC Recording found, skipping file: $line"
    else
        echo "${red}No JPEG found, creating file:${normal} $NewName"
        echo "File above being created from: $line"
        echo
        drawpile-cmd -a -A -platform offscreen "$line"
        echo
        echo
        echo "${red}Renaming file to user friendly readable format.${normal}"
        echo
        mv -T "$JPEGname" "$NewName" && echo ${green}"Renamed successfully." ${normal}
    fi

done
```
### **And this is the output in bash.**
![image](https://user-images.githubusercontent.com/18544575/62428956-0fb36500-b6bd-11e9-9383-bf15dbba8a55.png)

### **This is the rest of the script for converting last DPREC file in session to JPG.**
```
DprecArchiveFiles=$(find . -type f -name "*.dprec.archived" | sed 's/.\///g')
echo "$DprecArchiveFiles" | while IFS= read -r line ; 
do

    JPEGname=$( echo $line | sudo sed 's/.dprec.archived/-1.jpeg/g' ) ;
    SessionArchiveFile=$( echo "$line" | cut -c 1-36 ) ; 
    LastFileOfSession=$( egrep "^FILE" "$SessionArchiveFile".session.archived | tail -n 1 | cut -d ' ' -f 2-3 ).archived
    FileModDate=$(date -r "$line" "+%Y-%m-%d %H.%M.%S") ; 
    FileTitle=$(grep -m 1 "TITLE " "$SessionsFolder/$SessionArchiveFile".session.archived | cut -c 7-100) ; 
    NewName=$( echo $FileModDate - $FileTitle )
    echo
    echo ${bold}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${normal}
    echo
    if [[ "$LastFileOfSession" == "$line" ]]; then
        echo "Found last file in session series. Analyzing if JPG exists."
        echo
        if [[ -e $SessionsFolder/$NewName ]]; then
            echo "${green}JPEG Located${normal}: $NewName".jpeg
            echo "This file corresponds to DPREC Recording found, skipping file: $line"
        else
            echo "${red}No JPEG found, creating file:${normal} $NewName"
            echo "File above being created from: $line"
            echo
            drawpile-cmd -a -A -platform offscreen "$line"
            echo
            echo
            echo "${red}Renaming file to user friendly readable format.${normal}"
            echo
            mv -T "$JPEGname" "$NewName" && echo ${green}"Renamed successfully." ${normal}
        fi
    else
        echo "Not the last file in the archived session series. Moving on."
        echo
    fi

done
```

### **And this is it's corresponding output in bash.**
![image](https://user-images.githubusercontent.com/18544575/62428995-6f117500-b6bd-11e9-989d-6e50f03a3f4e.png)

**Comment by callaa** [comment] 2019-08-05 15:38
You can find the latest session recording file by looking at the session journal like this:

    grep "^FILE" $SESSION_FILE | cut -d ' ' -f 2- | tail -n 1

But you're right about the messy renaming. I'll have to take a look at that.

**Comment by callaa** [comment] 2019-08-06 15:42
This is now fixed in the master branch version.

**Closed by callaa** 2019-08-06 15:42 UTC
