### ISSUE TITLE
Crash when selecting different brush (android)

### ISSUE THREAD

**Issue by zetalambo** [drawpile/Drawpile#1108] opened 2023-07-11 19:48 UTC
**Version:** 2.2.0-beta.5-120-g723cbee9 (android apk)
**What happens:** Selecting a different brush preset crashes drawpile
**Steps to reproduce:**
-  Open android version
- Select any brush preset

I understand this is an unstable version for what I'm submitting an issue for. However, this exists in other stable release versions as well (I'm not sure which ones tbh, I just remember it persisting between versions)

**Comment by zetalambo** [comment] 2023-07-12 20:20
There are some good android emulators that you should be able to use to help development with the android version specifcally, although I'm not sure of the limitations of that. GenyMotion comes to mind from recommendations on reddit. Bluestacks, too.

Android version 9, although this happens on 13 as well, I believe it is the same error in logs there.

Style: Fusion, Krita Dark, and System (which uses system language)

[13:13:59 INFO] File logging started.
[13:14:05 INFO] File logging started.
[13:14:06 DEBUG] (null):0 ((null)): Database file '/data/user/0/net.drawpile/files/brushes.db' already exists
[13:14:06 DEBUG] (null):0 ((null)): Permissions of '/data/user/0/net.drawpile/files/brushes.db' are already read-write
[13:16:44 INFO] File logging started.
[13:16:44 DEBUG] (null):0 ((null)): Database file '/data/user/0/net.drawpile/files/brushes.db' already exists
[13:16:44 DEBUG] (null):0 ((null)): Permissions of '/data/user/0/net.drawpile/files/brushes.db' are already read-write

**Comment by askmeaboutlo0m** [comment] 2023-07-12 20:53
Emulator doesn't crash for me either. What is the system language of your devices?

**Comment by zetalambo** [comment] 2023-07-12 21:25
English (United States)

**Comment by askmeaboutlo0m** [comment] 2023-07-12 21:39
Alright, thanks for the information. I'll try to somehow reproduce it in an emulator or otherwise see about how to get debug logs out of the thing. Will probably be another while until I can get to it.

I guess meanwhile other things you could try is to check if you have any applications installed that interfere with Drawpile. Antivirus stuff is always a top contender for breaking stuff in terrible ways. As are applications that hijack accessibility features, some password managers do that for example.

**Comment by zetalambo** [comment] 2023-07-12 22:32
Update: Okay so turns out it was an accessibility feature killing off Drawpile. That would be the accessibility access from an app called Rotate, which allows the screen to be rotated differently than is typically possible (useful if you want to invite the portrait orientation of your homescreen for example). Same for macrodroid. After disabling those, no more crashes. So I don't think there's anything you could do to fix that, unfortunately.

**Comment by askmeaboutlo0m** [comment] 2023-07-14 04:08
It's still a bug here, even if it's caused by another program. Or probably a bug in Qt, but it might be possible to work around it in Drawpile, patch it ourselves or at least report it upstream. So I'd try to reproduce it still.

I tried to find Rotate, but didn't manage to since it's such s common name, do you have a link to it?

Macrodroid I did find, but didn't find a macro trigger that caused a crash, do you happen to know what's causing it specifically?

**Comment by zetalambo** [comment] 2023-07-14 14:56
Thank you very much for being willing to fix the bug, much appreciated.

https://play.google.com/store/apps/details?id=com.pranavpandey.rotation

The link above is for Rotation, apologies for the confusion, should have thought more about it being a very common name for apps. It's really easy to use and requests accessibility access, as mentioned previously. Not sure how it works internally

As for macrodroid, I'm not entirely sure what is causing it to crash. I do have a handful of plugins that I've used for reading screen contents that I'm no longer using, although upon removal those don't seem to affect drawpile's crashes.

Same for another app called Texpand, which looks for user-defined text while typing and allows the user to replace it with different or longer text. Same result as others. Only crashes when Installed Services under accessability are enabled. It doesn't seem to matter which one, even ones whose related processes are stopped, cache cleared along with data. It only takes one enabled to crash

**Comment by askmeaboutlo0m** [comment] 2023-08-18 20:25
Alright, I've finally gotten around to trying this: I can reproduce the issue, Rotation makes it crash like you said. It doesn't crash Krita, which has a similar dialog. I haven't gotten around to actually debugging it, but there's a path forward on this.

**Comment by askmeaboutlo0m** [comment] 2023-09-09 18:00
This should be fixed now. Not sure what Rotate has to do with it, but it was possible to get two simultaneous accesses to the brushes, which caused mayhem because they were stepping on each other. Now it's locked to doing one thing at a time.

The fix is available in the continuous development release: https://github.com/drawpile/Drawpile/releases/tag/continuous

Thanks for reporting it!

**Closed by askmeaboutlo0m** 2023-09-09 18:00 UTC
Labels: Bug
