### ISSUE TITLE
Layer opacity changes global instead of local.

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#445] opened 2017-04-10 23:49 UTC
I don't think this is a bug, but it would be better local instead of global.

IMO when I change the layer opacity it should change exclusively on my screen. But that isn't what happens: it changes the layer opacity for every user in the room. This is bad because I need to change the layer opacity several times while drawing but I don't want to bother other people changing the opacity of the layer where they're working on.

**Comment by callaa** [comment] 2017-04-11 06:18
This is technically possible, as the hide/show layer change works this way. However, a local only opacity change would need a user interface to make it clear the change is local-only. I think having the option to change it globally is desirable, depending on the use case, so some indication that the opacity has been locally overridden is needed.

**Comment by Le2222** [comment] 2017-04-11 10:29
For me it was a big surprise when I found that it isn't 'local' like the 'hide/show' layer (I asked a friend to be sure of it). I see you think different, but IMO the obvious/logical behavior would be the 'local' (like the show/hide wich is very similar) so the 'global' is the one that would demand an enlightening interface support.

**Comment by callaa** [comment] 2017-04-11 15:12
The visibility toggle is the only layer attribute that is local, and is marked as such, so at least to me the opacity being local would be surprising. I understand that for your workflow, a local opacity would be better, but I do not think this is the case for everyone. I'm sure I would start getting bug reports about the new behavior if I changed it.

However, an option to enable a local override mode for a layer would enable both workflows and might also make it clearer that the "hide layer" option is local only. The question is: how should the user interface look/work?

**Comment by notfood** [comment] 2017-04-11 15:21
It may make it too cluttered/confusing. Perhaps holding shift and slide/click to make it only local? Add some color to it to represent it's local only?

**Comment by Le2222** [comment] 2017-04-11 18:00
A world icon could mean 'global' while a computer icon could mean 'local'? I'll think about, if I get a better idea I'm going to share it here on this post.

**Comment by askmeaboutlo0m** [comment] 2023-03-23 12:44
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Whoops, #960 is a duplicate of this, but I already commented stuff there. I'll close this issue in favor of that other one, but the feature is still in discussion.

**Closed by askmeaboutlo0m** 2023-03-23 12:44 UTC
Labels: Feature
