### ISSUE TITLE
Drawpile newest version brings Issue #556 back

### ISSUE THREAD

**Issue by Miumix** [drawpile/Drawpile#568] opened 2018-02-25 20:23 UTC
This morning installed drawpile 2.0.9 to test it out. But sadly, disabling "bug workarounds" option to get rid of the annoying dots (#556) brings the distorting lineart back  (#346) once again .

![sobs](https://user-images.githubusercontent.com/13894094/36645835-1a7b347e-1a45-11e8-9056-c739595bd975.png)

I find this odd since previously I tried out the experimental version with support for Windows Ink and the latest releases fixed the current issue.
After that, I reinstalled drawpile from scratch by cleaning all traces of it but without success. 
Thanks for a prompt reply and the hard work as always ♥

**Comment by callaa** [comment] 2018-02-25 20:41
Hmm, it's probably related to the "mouse mode" support code I added, since that's the only thing that has changed between the experimental version and the final release. Those jagged edges at least look like they could be caused by the mouse mode workaround trying to sync up the tablet with the mouse.

For the next release I'll add an option to enable or disable the mouse mode workaround. In the mean time, you can use the experimental version, since there weren't many other important changes in this release.

**Comment by notfood** [comment] 2018-03-01 20:24
It seems to affect Linux as well. It's not subtle at all, happens when the line is swift and pressure is light, it doesn't seem to be the same on 2.0.8.

I recorded a demostration, same pressure curve, same pen settings, different Drawpile versions.

[![Video](https://img.youtube.com/vi/SRspGaTyXOM/0.jpg)](https://www.youtube.com/watch?v=SRspGaTyXOM)

**Comment by callaa** [comment] 2018-03-02 11:45
Is that with the bug workaround mode enabled or disabled? In any case, I doubt the cause is the same, since the Windows tablet code is entirely separate from the Linux code.

**Comment by notfood** [comment] 2018-03-02 20:08
Ah... disabling bug workaround mode fixed it for me. It was enabled in both.

**Comment by callaa** [comment] 2018-03-02 22:12
That's good to hear. I think I should probably remove the bug workaround mode. With the new tablet event handler code, it seems to be causing more problems than it solves.

**Comment by callaa** [comment] 2018-03-17 16:11
This should now be fixed in version 2.0.10

**Closed by callaa** 2018-03-17 16:11 UTC
Labels: Tablet

**Comment by Miumix** [comment] 2018-03-18 19:04
![beautifulupdate](https://user-images.githubusercontent.com/13894094/37569766-797a0cc4-2abd-11e8-8ab4-0bfe358db33c.png)
Works pretty well ♥
Thank you very much, Calla~
