### ISSUE TITLE
my server wont show up in the server list

### ISSUE THREAD

**Issue by LadyLilligant** [drawpile/Drawpile#402] opened 2017-02-17 02:54 UTC
i created a server yet it wont show up in the server list for my friend to join

**Comment by callaa** [comment] 2017-02-17 06:36
I need a bit more information. Do you see any error messages? Are you using the public server or your own? If you're using your own server, do you have a custom `host-addr` setting?

**Comment by LadyLilligant** [comment] 2017-02-17 12:01
Public server and no I don't

**Comment by callaa** [comment] 2017-02-17 15:01
Thanks. Looks like announcements from the public server aren't working for anyone else either, except for one which predates the list server update I did the day before yesterday. I think I know where the bug is. I should have a fix ready soon.

**Comment by LadyLilligant** [comment] 2017-02-17 15:23
Ok cool

**Comment by callaa** [comment] 2017-02-17 15:51
Alright, it's fixed now.

The problem was caused by the new list server version I installed. The new version checks that the hostname field is valid and matches the announcer IP address. The problem was that the list server and the public server both run on the same server machine, so when drawpile-srv made a listing request, the request came from the loopback address. The listing server looked at the requests and said "Nope. drawpile.net does not resolve to 127.0.0.1" and refused the announcement. This is why the announcements continued working for all other servers.

**Closed by callaa** 2017-02-17 15:51 UTC
