### ISSUE TITLE
Selection Gradient Fill

### ISSUE THREAD

**Issue by amoruwu** [drawpile/Drawpile#1322] opened 2024-06-30 05:17 UTC
With the new updates to selections Gradient tool is now possible in Drawpile! and it would be a game changer! 

I believe Gradient fill would be great, yet it should only be used in selections. Since using it in a public board without a selection would be a utter disaster. 
![e2e51b3bf0405d2ccedc86c416aaaa7c](https://github.com/drawpile/Drawpile/assets/78520579/b0e2b2af-4e6d-40c6-a980-bb1abdfe3996)

**Comment by askmeaboutlo0m** [comment] 2024-06-30 13:52
Yep, selections now allow for stuff like gradient fills, filters etc. This is a duplicate of #293 though.

**Closed by askmeaboutlo0m** 2024-06-30 13:52 UTC
