### ISSUE TITLE
(2.1.12) Shift key modifier doesn't work, and renders as distorted Unicode character in the settings

### ISSUE THREAD

**Issue by Banderi** [drawpile/Drawpile#808] opened 2019-10-22 20:07 UTC
(on Windows 10 Pro here, can say it happens to my friend on Home as well)

The "shift" modifier (I assume) displays as this odd low-res Unicode symbol, and doesn't seem to do anything for the modifiers. Maybe is it because of a single issue that prevents it from working properly?

![image](https://user-images.githubusercontent.com/16541079/67327233-e665e080-f517-11e9-936a-2de97d2927d9.png)

**Comment by callaa** [comment] 2019-10-23 18:33
This one I'm unable to reproduce. The weird glyph is probably just a font issue. The easiest fix will be to just use the word "shift" instead of the character.

However, the shift modifier works fine here. I've tested it on Linux and macOS, so it could be a Windows specific problem.

**Comment by callaa** [comment] 2019-12-22 13:14
Fixed in the current version. Instead of a glyph, the word "Shift" is now used.

**Closed by callaa** 2019-12-22 13:14 UTC
